// Copyright (c) 2026 Physalia Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Text.Json;
using GH_IO.Serialization;
using Grasshopper.Kernel;
using Grasshopper.Kernel.Parameters;
using Grasshopper.Kernel.Special;
using Physalia.Core.Parsing;
using Physalia.Core.Prompts;
using Physalia.GH.Attributes;
using Physalia.GH.Helpers;

namespace Physalia.GH.Components;

/// <summary>
/// The CLUSTER RECEIVER component hosts a Grasshopper cluster generated by a paired TRANSMITTER.
/// Its input and output parameters are rebuilt dynamically from the LLM response.
/// </summary>
public class ClusterReceiver : ReceiverBase, IGH_DocumentOwner
{
    // FIELDS ==========================================================================================

    // The live inner document. Replaced with a fresh instance on each re-open so that
    // GH_Document.Read() always starts from a clean slate (avoids NRE from stale internal state
    // left by GH's close cycle on the previous instance).
    private GH_Document _internalDocument;

    // Snapshot of the inner document as XML. Captured in DocumentClosed before GH clears
    // the document's objects. Restored into a fresh document on next OpenEditor or SolveInstance.
    private string? _snapshotXml;

    // Maps outer input/output parameter InstanceGuid → inner hook InstanceGuid.
    // Rebuilt by SyncHooks() whenever parameters change or the inner document is restored.
    private Dictionary<Guid, Guid> _inputHookMap = new();
    private Dictionary<Guid, Guid> _outputHookMap = new();

    // Guards DocumentModified against re-entering ExpireSolution during our own solve cycle.
    private bool _solving;

    // Guards SyncOuterFromInner from running while SyncHooks() is pushing outer → inner,
    // preventing a re-entrant reverse sync.
    private bool _syncingHooks;

    // Parsed response from the last LLM call; null until a response has been received.
    private ClusterResponse? _lastResponse;

    // Component-not-found and wire-resolution errors from the last ApplyLlmResponse call.
    // Reported by GetFixMessage() so the auto-fix loop can correct them.
    private List<string> _lastClusterErrors = new();

    // Runtime errors/warnings collected from inner components after the last NewSolution call.
    // Reported by GetFixMessage() alongside construction errors.
    private List<string> _lastInnerRuntimeErrors = new();

    // PROPERTIES =======================================================================================

    /// <summary>
    /// Gets the unique ID for this component. Do not change this ID after release.
    /// </summary>
    public override Guid ComponentGuid
        => new Guid("53CE5F69-9A62-40A7-BBF7-85A88977D097");

    /// <summary>
    /// Gets the system prompt fragment describing the cluster format and JSON response schema.
    /// Combined with <see cref="Physalia.Core.Prompts.SystemPrompt.Preamble"/> by TRANSMITTER.
    /// The installed plugin list is injected at access time so it reflects the user's current environment.
    /// </summary>
    public override string FormatPrompt
    {
        get
        {
            var plugins = GHSystemHelpers.GetInstalledPluginNames();
            return SystemPrompt.GetClusterPrompt(plugins);
        }
    }

    /// <summary>
    /// Gets the current state of this Receiver. Returns null until a response has been received.
    /// </summary>
    public override string? State => _lastResponse?.StatusMessage;

    /// <summary>
    /// Gets a description of this Receiver's current inputs, outputs, and functionality.
    /// Returns null until a response has been received.
    /// </summary>
    public override string? ReceiverDescription => _lastResponse?.StatusMessage;

    // CONSTRUCTOR =======================================================================================

    /// <summary>
    /// Initializes a new instance of the <see cref="ClusterReceiver"/> class.
    /// </summary>
    public ClusterReceiver()
        : base(
            "ClusterReceiver",
            "ClZ",
            "Generated Grasshopper Cluster",
            "Core")
    {
        // IconPath = "Physalia.GH.Resources.microbe.png";
        _internalDocument = MakeFreshDocument();
    }

    // GH COMPONENT OVERRIDES ============================================================================================

    /// <summary>
    /// No fixed input parameters are registered; all inputs are added dynamically via
    /// <see cref="ApplyLlmResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The input parameter manager (unused).</param>
    protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
    {
    }

    /// <summary>
    /// No fixed output parameters are registered; all outputs are added dynamically via
    /// <see cref="ApplyLlmResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The output parameter manager (unused).</param>
    protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
    {
    }

    /// <summary>
    /// Pushes outer input data into the inner document's cluster input hooks,
    /// solves the inner document, then pulls results from the cluster output hooks
    /// back into this component's output parameters.
    /// </summary>
    /// <param name="DA">The DA object is used to retrieve from inputs and store in outputs.</param>
    protected override void SolveInstance(IGH_DataAccess DA)
    {
        // Let the inner document manage all data tree logic; receive everything in one pass.
        DA.DisableGapLogic();
        if (DA.Iteration > 0)
            return;

        _solving = true;
        _lastInnerRuntimeErrors.Clear();
        try
        {
            EnsureLiveDocument();

            // 1. Push outer inputs → inner input hooks
            for (int i = 0; i < Params.Input.Count; i++)
            {
                IGH_Param outer = Params.Input[i];
                if (!_inputHookMap.TryGetValue(outer.InstanceGuid, out Guid hookGuid))
                    continue;

                IGH_Param? hook = _internalDocument.FindParameter(hookGuid);
                if (hook == null)
                    continue;

                hook.ClearData();
                hook.ExpireSolution(false);
                if (outer.VolatileData?.PathCount > 0)
                    hook.AddVolatileDataTree(outer.VolatileData);
            }

            // 2. Solve the inner document
            _internalDocument.Enabled = true;
            _internalDocument.NewSolution(false);
            _internalDocument.Enabled = false;

            // 3. Collect runtime errors/warnings from inner components and surface them
            CollectInnerRuntimeErrors();

            // 4. Pull inner output hooks → outer output parameters
            for (int k = 0; k < Params.Output.Count; k++)
            {
                IGH_Param outer = Params.Output[k];
                if (!_outputHookMap.TryGetValue(outer.InstanceGuid, out Guid hookGuid))
                    continue;

                IGH_Param? hook = _internalDocument.FindParameter(hookGuid);
                if (hook == null)
                    continue;

                outer.VolatileData.Clear();
                outer.AddVolatileDataTree(hook.VolatileData);
            }
        }
        finally
        {
            _solving = false;
        }
    }

    /// <summary>
    /// Assigns the custom <see cref="ReceiverAttrib"/> attribute class to this component.
    /// </summary>
    public override void CreateAttributes() => m_attributes = new ReceiverAttrib(this);

    /// <summary>
    /// Re-subscribes rename listeners for all user-defined parameters after the component is loaded into a document.
    /// </summary>
    /// <param name="document">The document this component was added to.</param>
    public override void AddedToDocument(GH_Document document)
    {
        base.AddedToDocument(document);
        SubscribeUserParamEvents();
    }

    /// <summary>
    /// Removes the internal document from the GH document server when this component is deleted.
    /// </summary>
    /// <param name="document">The document this component was removed from.</param>
    public override void RemovedFromDocument(GH_Document document)
    {
        var server = Grasshopper.Instances.DocumentServer;
        if (server.Contains(_internalDocument))
            server.SafeRemoveDocument(_internalDocument);

        base.RemovedFromDocument(document);
    }

    /// <summary>
    /// Extends the base parameter maintenance to keep inner document hooks in sync
    /// whenever the outer parameter list changes.
    /// </summary>
    public override void VariableParameterMaintenance()
    {
        base.VariableParameterMaintenance();

        // Only sync while the inner document is live; if a snapshot is pending the
        // sync will happen automatically when EnsureLiveDocument is next called.
        if (_snapshotXml == null)
            SyncHooks();
    }

    // SERIALIZATION ==========================================================================

    /// <summary>
    /// Serializes the cluster state so it survives save and reload.
    /// Uses <see cref="_snapshotXml"/> as the source of truth when the inner document
    /// has been cleared by GH (after Save and Close), falling back to the live document.
    /// </summary>
    /// <param name="writer">The GH_IWriter to write to.</param>
    /// <returns>true.</returns>
    public override bool Write(GH_IWriter writer)
    {
        string xml;
        if (_snapshotXml != null)
        {
            xml = _snapshotXml;
        }
        else
        {
            var archive = new GH_Archive();
            archive.AppendObject(_internalDocument, "ClusterDoc");
            xml = archive.Serialize_Xml();
        }

        writer.SetString("InternalDocumentXml", xml);

        if (_lastResponse != null)
            writer.SetString("ClusterResponseJson", JsonSerializer.Serialize(_lastResponse));

        return base.Write(writer);
    }

    /// <summary>
    /// Deserialises the cluster state. Stores the XML in <see cref="_snapshotXml"/>
    /// so the inner document can be restored into a fresh instance on first use.
    /// </summary>
    /// <param name="reader">The GH_IReader to read from.</param>
    /// <returns>true.</returns>
    public override bool Read(GH_IReader reader)
    {
        if (reader.ItemExists("InternalDocumentXml"))
            _snapshotXml = reader.GetString("InternalDocumentXml");

        string responseJson = string.Empty;
        if (reader.TryGetString("ClusterResponseJson", ref responseJson))
            _lastResponse = JsonSerializer.Deserialize<ClusterResponse>(responseJson);

        return base.Read(reader);
    }

    // EDITOR ========================================================================

    /// <summary>
    /// Opens the internal Grasshopper document in the GH editor, the same way a native
    /// cluster component does when double-clicked. Restores from snapshot if needed,
    /// then switches the active canvas to show the inner document.
    /// </summary>
    public override void OpenEditor()
    {
        EnsureLiveDocument();

        var server = Grasshopper.Instances.DocumentServer;
        _internalDocument.Enabled = true;
        server.PromoteDocument(_internalDocument);
        Grasshopper.Instances.ActiveCanvas.Document = _internalDocument;
    }

    // LLM RESPONSE ==================================================================

    /// <summary>
    /// Parses the raw LLM response, rebuilds the outer parameters, and reconstructs the inner
    /// document with the described components and wires.
    /// </summary>
    /// <param name="rawResponse">The raw JSON string returned by the LLM.</param>
    public override void ApplyLlmResponse(string rawResponse)
    {
        _lastResponse = ResponseParser.ParseCluster(rawResponse);
        LastStatusMessage = _lastResponse.StatusMessage;
        _lastClusterErrors.Clear();

        var outputParamDefs = _lastResponse.Outputs
            .Select(o => new ParamDefinition { Name = o.Name, PrettyName = o.PrettyName, Tooltip = o.Tooltip })
            .ToList();

        EnsureLiveDocument();

        // Suppress inner document events for the entire rebuild to prevent DocumentModified
        // firing mid-rebuild, which would trigger SyncOuterFromInner while hooks are wired
        // and their NickName getters return the connected component's param name rather than
        // CustomNickName, causing spurious outer params and a corrupted hook map.
        // WithEventsSuppressed is re-entrant-safe, so nested calls from sub-methods are fine.
        WithEventsSuppressed(() =>
        {
            ClearInnerDocument();

            // Only rebuild outer params on the first response. Once params are established
            // the LLM is instructed never to add, remove, or rename them, so subsequent
            // calls (including autofix) must not alter the outer parameter list.
            if (Params.Input.Count == 0 && Params.Output.Count == 0)
                ParamBuilder.Rebuild(this, _lastResponse.Inputs, outputParamDefs);

            // Create hooks before BuildInnerDocument wires to them. OnParametersChanged inside
            // ParamBuilder.Rebuild may not call VariableParameterMaintenance synchronously.
            SyncHooks();

            BuildInnerDocument(_lastResponse);
        });

        ExpireSolution(true);
    }

    /// <summary>
    /// Builds a fix prompt from any component-not-found, wiring, or runtime errors recorded
    /// since the last <see cref="ApplyLlmResponse"/> call. Returns null if there are no errors.
    /// </summary>
    /// <returns>A formatted error message, or null if there are no errors.</returns>
    public override string? GetFixMessage()
    {
        if (_lastClusterErrors.Count == 0 && _lastInnerRuntimeErrors.Count == 0)
            return null;

        var sb = new StringBuilder();
        sb.AppendLine("The cluster has errors. Return a corrected JSON response in the same format.");

        if (_lastClusterErrors.Count > 0)
        {
            sb.AppendLine();
            foreach (var err in _lastClusterErrors)
                sb.AppendLine($"  - {err}");
        }

        if (_lastInnerRuntimeErrors.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("Runtime errors from inner components:");
            foreach (var err in _lastInnerRuntimeErrors)
                sb.AppendLine($"  - {err}");
        }

        // Append the live document structure so the LLM has exact NickNames for wiring.
        var structure = GHSystemHelpers.DescribeDocumentStructure(GhDocState.FromDocument(_internalDocument));
        if (!string.IsNullOrEmpty(structure))
        {
            sb.AppendLine();
            sb.AppendLine("Current inner document state (use exact NickNames for wiring):");
            sb.Append(structure);
        }

        return sb.ToString();
    }

    /// <summary>
    /// Returns the current cluster structure for injection into fresh LLM prompts, by walking
    /// the live inner document. This captures manual user edits to the cluster as well as
    /// LLM-generated state. Falls back to the last LLM response if the live document is empty.
    /// Returns null if no response has been received yet.
    /// </summary>
    /// <returns>A formatted description of the current cluster state, or null if no state exists.</returns>
    public override string? GetCurrentStatePrompt()
    {
        if (_lastResponse == null)
            return null;

        var structure = GHSystemHelpers.DescribeDocumentStructure(GhDocState.FromDocument(_internalDocument));
        if (!string.IsNullOrEmpty(structure))
            return $"The current cluster state is:\n{structure}";

        // Fall back to last LLM response if the live document is not yet populated.
        var json = JsonSerializer.Serialize(_lastResponse, new JsonSerializerOptions { WriteIndented = true });
        return $"The current cluster state is:\n{json}";
    }

    // IGH_DOCUMENT OWNER ====================================================================

    /// <summary>
    /// Called by the inner document when its contents change.
    /// Expires this component so its outputs are recalculated, and syncs any newly placed
    /// inner hooks back to outer params — both only outside of our own solve/sync cycles
    /// to prevent re-entrance.
    /// </summary>
    /// <param name="document">The inner document that was modified.</param>
    public void DocumentModified(GH_Document document)
    {
        if (!_solving)
            ExpireSolution(true);

        if (!_solving && !_syncingHooks && _snapshotXml == null)
            SyncOuterFromInner();
    }

    /// <summary>
    /// Called by the inner document when it is closed (Save &amp; Close). Snapshots the
    /// current document state to XML before GH clears the document's objects.
    /// </summary>
    /// <param name="document">The inner document that was closed.</param>
    public void DocumentClosed(GH_Document document)
    {
        var archive = new GH_Archive();
        archive.AppendObject(_internalDocument, "ClusterDoc");
        _snapshotXml = archive.Serialize_Xml();

        // Hook maps are keyed by current outer-param GUIDs and will be rebuilt from
        // the restored snapshot by SyncHooks() the next time EnsureLiveDocument() runs.
        _inputHookMap.Clear();
        _outputHookMap.Clear();
    }

    /// <summary>
    /// Returns the parent GH document that contains this component.
    /// </summary>
    /// <returns>The parent <see cref="GH_Document"/>.</returns>
    public GH_Document OwnerDocument() => OnPingDocument();

    // PRIVATE HELPERS ====================================================================

    /// <summary>
    /// Creates a new <see cref="GH_Document"/> with this component set as owner.
    /// </summary>
    private GH_Document MakeFreshDocument()
    {
        return new GH_Document
        {
            Owner = this,
            Nested = true,
        };
    }

    /// <summary>
    /// Runs <paramref name="action"/> with inner-document events suppressed, restoring the
    /// previous event state afterwards. Safe to call recursively — each layer saves and
    /// restores the state it found, so nested calls always leave events in the correct state.
    /// </summary>
    private void WithEventsSuppressed(Action action)
    {
        bool wasRaisingEvents = _internalDocument.RaiseEvents;
        _internalDocument.RaiseEvents = false;
        try
        {
            action();
        }
        finally
        {
            _internalDocument.RaiseEvents = wasRaisingEvents;
        }
    }

    /// <summary>
    /// Creates a new generic outer parameter mapped to the given NickName.
    /// Used by <see cref="SyncOuterFromInner"/> when registering hooks as outer params.
    /// </summary>
    private static Param_GenericObject MakeOuterParam(string nickName) =>
        new Param_GenericObject
        {
            Name = nickName,
            NickName = nickName,
            Description = "user defined parameter",
            Optional = true,
        };

    /// <summary>
    /// Ensures <see cref="_internalDocument"/> is registered on the GH document server and
    /// its objects are fully initialised. If a snapshot is pending it is restored into a fresh
    /// document first. After restoring, <see cref="SyncHooks"/> reconciles the cluster hooks
    /// with the current outer parameter list.
    /// </summary>
    private void EnsureLiveDocument()
    {
        var server = Grasshopper.Instances.DocumentServer;

        // Fast path: document is already live on the server with no snapshot pending.
        if (_snapshotXml == null && server.Contains(_internalDocument))
            return;

        // Remove the stale document from the server if it is still registered
        // (e.g. an immediate re-open before GH had a chance to remove it).
        if (server.Contains(_internalDocument))
        {
            _internalDocument.IsModified = false;
            server.SafeRemoveDocument(_internalDocument);
        }

        // Always start from a fresh document — GH_Document.Read() must start from a clean slate.
        _internalDocument = MakeFreshDocument();

        // Add to server BEFORE restoring snapshot — AddDocument sets up RhinoDocument
        // on the document, which GH_Document.Read() accesses internally and NREs without.
        server.AddDocument(_internalDocument);
        _internalDocument.Owner = this;
        _internalDocument.Nested = true;

        if (_snapshotXml != null)
        {
            var archive = new GH_Archive();
            if (archive.Deserialize_Xml(_snapshotXml))
            {
                // Suppress events during Read() to avoid cascading solution cycles.
                WithEventsSuppressed(() => archive.ExtractObject(_internalDocument, "ClusterDoc"));
            }

            _snapshotXml = null;
        }

        // Re-assert after restore in case Read() cleared them.
        _internalDocument.Owner = this;
        _internalDocument.Nested = true;

        SyncHooks();
    }

    /// <summary>
    /// Synchronises the inner document's <see cref="GH_ClusterInputHook"/> and
    /// <see cref="GH_ClusterOutputHook"/> instances to match the current outer parameter list.
    /// Hooks are matched by NickName so existing internal wiring is preserved across rebuilds.
    /// New hooks are created for new outer params; orphaned hooks are removed.
    /// </summary>
    private void SyncHooks()
    {
        if (_internalDocument == null)
            return;

        // _syncingHooks prevents DocumentModified from triggering a reverse sync while
        // we are in the middle of pushing outer → inner changes.
        _syncingHooks = true;
        try
        {
            // Suppress document events to prevent cascading solution cycles mid-sync.
            WithEventsSuppressed(() =>
            {
                SyncHookSide(
                    Params.Input,
                    _internalDocument.ClusterInputHooks(),
                    ref _inputHookMap,
                    isInput: true);

                SyncHookSide(
                    Params.Output,
                    _internalDocument.ClusterOutputHooks(),
                    ref _outputHookMap,
                    isInput: false);
            });
        }
        finally
        {
            _syncingHooks = false;
        }
    }

    /// <summary>
    /// Reverse-syncs outer params from the inner document's hooks. Called from
    /// <see cref="DocumentModified"/> when the user places a hook on the inner canvas.
    /// Creates an outer param for any hook that has no corresponding outer param by NickName.
    /// </summary>
    private void SyncOuterFromInner()
    {
        var inputHooks = _internalDocument.ClusterInputHooks() ?? Array.Empty<IGH_Param>();
        var outputHooks = _internalDocument.ClusterOutputHooks() ?? Array.Empty<IGH_Param>();

        var outerInputNicks = new HashSet<string>(Params.Input.Select(p => p.NickName));
        var outerOutputNicks = new HashSet<string>(Params.Output.Select(p => p.NickName));

        bool changed = false;

        foreach (var hook in inputHooks)
        {
            if (outerInputNicks.Contains(hook.NickName))
                continue;

            var param = MakeOuterParam(hook.NickName);
            Params.RegisterInputParam(param);
            _inputHookMap[param.InstanceGuid] = hook.InstanceGuid;
            changed = true;
        }

        foreach (var hook in outputHooks)
        {
            if (outerOutputNicks.Contains(hook.NickName))
                continue;

            var param = MakeOuterParam(hook.NickName);
            Params.RegisterOutputParam(param);
            _outputHookMap[param.InstanceGuid] = hook.InstanceGuid;
            changed = true;
        }

        if (changed)
        {
            Params.OnParametersChanged();
            ExpireSolution(true);
        }
    }

    // Syncs one side (inputs or outputs) of the hook mapping.
    // existingHooks is GH_ClusterInputHook[] or GH_ClusterOutputHook[]; both implement IGH_Param.
    private void SyncHookSide(
        List<IGH_Param> outerParams,
        IGH_Param[]? existingHooks,
        ref Dictionary<Guid, Guid> hookMap,
        bool isInput)
    {
        var hooks = existingHooks ?? Array.Empty<IGH_Param>();

        // GUID map: used as the primary lookup. Survives post-wiring NickName changes because
        // GH_ClusterHook.NickName walks sources/recipients once wired, returning the connected
        // component's param name instead of our CustomNickName — making NickName-only matching
        // unreliable after BuildInnerDocument has run.
        var byGuid = hooks.ToDictionary(h => h.InstanceGuid);

        // NickName map: fallback for snapshot restoration, where all hook GUIDs are new
        // (fresh document) and the existing hookMap is empty.
        var byNick = new Dictionary<string, IGH_Param>(StringComparer.Ordinal);
        foreach (var h in hooks)
            byNick.TryAdd(h.NickName, h);

        var newMap = new Dictionary<Guid, Guid>(outerParams.Count);
        var usedGuids = new HashSet<Guid>();

        for (int i = 0; i < outerParams.Count; i++)
        {
            IGH_Param outer = outerParams[i];

            // Primary: look up by the GUID we recorded the last time this outer param was synced.
            IGH_Param? existingHook = null;
            if (hookMap.TryGetValue(outer.InstanceGuid, out Guid knownGuid))
                byGuid.TryGetValue(knownGuid, out existingHook);

            // Fallback: NickName match (handles snapshot restore where GUIDs are all new).
            if (existingHook == null)
                byNick.TryGetValue(outer.NickName, out existingHook);

            if (existingHook != null)
            {
                // Re-assert Custom* overrides so the hook ignores source/recipient name inheritance.
                var existingClusterHook = (GH_ClusterHook)existingHook;
                existingClusterHook.CustomName = outer.NickName;
                existingClusterHook.CustomNickName = outer.NickName;
                newMap[outer.InstanceGuid] = existingHook.InstanceGuid;
                usedGuids.Add(existingHook.InstanceGuid);
            }
            else
            {
                // Create a new hook and place it on the inner canvas.
                IGH_Param newHook = isInput
                    ? (IGH_Param)new GH_ClusterInputHook()
                    : (IGH_Param)new GH_ClusterOutputHook();

                var clusterHook = (GH_ClusterHook)newHook;
                clusterHook.CustomName = outer.NickName;
                clusterHook.CustomNickName = outer.NickName;
                newHook.CreateAttributes();
                newHook.Attributes.Pivot = new PointF(isInput ? 50f : 500f, 100f + i * 60f);

                _internalDocument.AddObject(newHook, update: false);
                newMap[outer.InstanceGuid] = newHook.InstanceGuid;
                usedGuids.Add(newHook.InstanceGuid);
            }
        }

        // Remove hooks that are no longer needed (not matched to any current outer param).
        // Use GUID identity rather than NickName to avoid false positives from wired NickName drift.
        foreach (var hook in hooks)
        {
            if (!usedGuids.Contains(hook.InstanceGuid))
                _internalDocument.RemoveObject(hook, false);
        }

        hookMap = newMap;
    }

    /// <summary>
    /// Syncs inner document hooks and expires the solution when a user renames an outer param.
    /// </summary>
    /// <param name="p">The renamed parameter.</param>
    protected override void AfterParamNickNameChanged(IGH_Param p)
    {
        if (_snapshotXml == null)
            SyncHooks();

        ExpireSolution(true);
    }

    // Removes all objects from the inner document with events suppressed.
    private void ClearInnerDocument()
    {
        WithEventsSuppressed(() =>
        {
            foreach (var obj in _internalDocument.Objects.ToList())
                _internalDocument.RemoveObject(obj, false);

            _inputHookMap.Clear();
            _outputHookMap.Clear();
        });
    }

    // Collects runtime errors and warnings from all objects in the inner document,
    // surfaces them on this component's bubble, and stores them for GetFixMessage().
    private void CollectInnerRuntimeErrors()
    {
        foreach (var (level, msg) in GHSystemHelpers.CollectErrors(_internalDocument))
        {
            _lastInnerRuntimeErrors.Add(msg);
            AddRuntimeMessage(level, $"Inner {msg}");
        }
    }

    // Coordinates the full inner-document build: places objects, wires inputs and output hooks,
    // then applies hierarchical layout. All mutations are wrapped in WithEventsSuppressed so
    // DocumentModified cannot fire mid-build and corrupt the hook maps.
    private void BuildInnerDocument(ClusterResponse response)
    {
        WithEventsSuppressed(() =>
        {
            var state = GHSystemHelpers.PlaceObjects(_internalDocument, response.Components);
            GHSystemHelpers.WireComponentInputs(response.Components, state);
            GHSystemHelpers.WireOutputHooks(response.Outputs, state);
            _lastClusterErrors.AddRange(state.Errors);

            // Assign canvas positions to all inner objects using a left-to-right
            // hierarchical layout based on data-flow depth.
            HierarchicalLayout.Apply(_internalDocument, state.PanelTargets);
        });
    }

}
