// Copyright (c) 2026 Physalia Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Text.RegularExpressions;
using GH_IO.Serialization;
using Grasshopper.Kernel;
using Physalia.GH.Attributes;

namespace Physalia.GH.Components;

/// <summary>
/// The CLUSTER ZOOID component hosts a Grasshopper cluster generated by a paired COMPOSER.
/// Its input and output parameters are rebuilt dynamically from the LLM response.
/// </summary>
public class ClusterZooid : ZooidBase, IGH_DocumentOwner
{
    // FIELDS ==========================================================================================

    // The live inner document. Replaced with a fresh instance on each re-open so that
    // GH_Document.Read() always starts from a clean slate (avoids NRE from stale internal state
    // left by GH's close cycle on the previous instance).
    private GH_Document _internalDocument;

    // Snapshot of the inner document as XML. Captured in DocumentClosed before GH clears
    // the document's objects. Restored into a fresh document in OpenEditor. Also the
    // source of truth for file Write/Read serialization when the inner doc is not live.
    private string? _snapshotXml;

    // PROPERTIES =======================================================================================

    /// <summary>
    /// Gets the unique ID for this component. Do not change this ID after release.
    /// </summary>
    public override Guid ComponentGuid
    {
        get { return new Guid("50F82419-28B2-4661-9677-C6B0D718CDC7"); }
    }

    /// <summary>
    /// Gets the system prompt fragment describing the cluster format and JSON response schema.
    /// Combined with <see cref="Physalia.Core.Prompts.SystemPrompt.Preamble"/> by COMPOSER.
    /// </summary>
    public override string FormatPrompt => "Cluster format prompt — to be defined.";

    /// <summary>
    /// Gets the current state of this Zooid. Returns null until a response has been received.
    /// </summary>
    public override string? State => null;

    /// <summary>
    /// Gets a description of this Zooid's current inputs, outputs, and functionality.
    /// Returns null until a response has been received.
    /// </summary>
    public override string? ZooidDescription => null;

    // CONSTRUCTOR =======================================================================================

    /// <summary>
    /// Initializes a new instance of the <see cref="ClusterZooid"/> class.
    /// </summary>
    public ClusterZooid()
        : base(
            "ClusterZooid",
            "ClZ",
            "Generated Grasshopper Cluster",
            "Core")
    {
        _internalDocument = MakeFreshDocument();
    }

    // GH COMPONENT OVERRIDES ============================================================================================

    /// <summary>
    /// No fixed input parameters are registered; all inputs are added dynamically via
    /// <see cref="ApplyLlmResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The input parameter manager (unused).</param>
    protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
    {
    }

    /// <summary>
    /// No fixed output parameters are registered; all outputs are added dynamically via
    /// <see cref="ApplyLlmResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The output parameter manager (unused).</param>
    protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
    {
    }

    /// <summary>
    /// Executes the cluster. Not yet implemented.
    /// </summary>
    /// <param name="DA">The DA object is used to retrieve from inputs and store in outputs.</param>
    protected override void SolveInstance(IGH_DataAccess DA)
    {
    }

    /// <summary>
    /// Assigns the custom <see cref="ZooidAttrib"/> attribute class to this component.
    /// </summary>
    public override void CreateAttributes() => m_attributes = new ZooidAttrib(this);

    /// <summary>
    /// Re-subscribes rename listeners for all user-defined parameters after the component is loaded into a document.
    /// </summary>
    /// <param name="document">The document this component was added to.</param>
    public override void AddedToDocument(GH_Document document)
    {
        base.AddedToDocument(document);
        SubscribeUserParamEvents();
    }

    /// <summary>
    /// Removes the internal document from the GH document server when this component is deleted.
    /// </summary>
    /// <param name="document">The document this component was removed from.</param>
    public override void RemovedFromDocument(GH_Document document)
    {
        var server = Grasshopper.Instances.DocumentServer;
        if (server.Contains(_internalDocument))
        {
            server.SafeRemoveDocument(_internalDocument);
        }

        base.RemovedFromDocument(document);
    }

    // SERIALIZATION ==========================================================================

    /// <summary>
    /// Serializes the cluster state so it survives save and reload.
    /// Uses <see cref="_snapshotXml"/> as the source of truth when the inner document
    /// has been cleared by GH (after Save and Close), falling back to the live document.
    /// </summary>
    /// <param name="writer">The GH_IWriter to write to.</param>
    /// <returns>true.</returns>
    public override bool Write(GH_IWriter writer)
    {
        string xml;
        if (_snapshotXml != null)
        {
            // GH cleared the live document — use the snapshot captured in DocumentClosed.
            xml = _snapshotXml;
        }
        else
        {
            var archive = new GH_Archive();
            archive.AppendObject(_internalDocument, "ClusterDoc");
            xml = archive.Serialize_Xml();
        }

        writer.SetString("InternalDocumentXml", xml);
        return base.Write(writer);
    }

    /// <summary>
    /// Deserialises the cluster state. Stores the XML in <see cref="_snapshotXml"/>
    /// so <see cref="OpenEditor"/> can restore it into a fresh document on first open.
    /// </summary>
    /// <param name="reader">The GH_IReader to read from.</param>
    /// <returns>true.</returns>
    public override bool Read(GH_IReader reader)
    {
        if (reader.ItemExists("InternalDocumentXml"))
        {
            _snapshotXml = reader.GetString("InternalDocumentXml");
        }

        return base.Read(reader);
    }

    // EDITOR ========================================================================

    /// <summary>
    /// Opens the internal Grasshopper document in the GH editor, the same way a native
    /// cluster component does when double-clicked. If a snapshot exists, a fresh
    /// <see cref="GH_Document"/> is created and populated from it, avoiding NREs that
    /// occur when calling Read() on a document that has already been through a GH close cycle.
    /// </summary>
    public override void OpenEditor()
    {
        var server = Grasshopper.Instances.DocumentServer;

        // Remove the old document from the server if it is still registered
        // (e.g. an immediate re-open before GH had a chance to remove it).
        if (server.Contains(_internalDocument))
        {
            _internalDocument.IsModified = false;
            server.SafeRemoveDocument(_internalDocument);
        }

        // Always start from a fresh document — GH_Document.Read() must start from a clean slate.
        _internalDocument = MakeFreshDocument();

        // Add to server BEFORE restoring snapshot — AddDocument sets up RhinoDocument
        // on the document, which GH_Document.Read() accesses internally and NREs without.
        server.AddDocument(_internalDocument);
        _internalDocument.Owner = this;
        _internalDocument.Nested = true;

        // Restore from snapshot if one exists (left by DocumentClosed or file Read).
        if (_snapshotXml != null)
        {
            var archive = new GH_Archive();
            if (archive.Deserialize_Xml(_snapshotXml))
            {
                // Suppress events during Read() — without this, DocumentModified fires
                // for each object added, which can cascade into a solution cycle that
                // accesses partially-initialised document state and causes a NRE.
                _internalDocument.RaiseEvents = false;
                archive.ExtractObject(_internalDocument, "ClusterDoc");
                _internalDocument.RaiseEvents = true;
            }

            _snapshotXml = null;
        }

        // Re-assert after restore in case Read() cleared them.
        _internalDocument.Owner = this;
        _internalDocument.Nested = true;

        // PromoteDocument reorders the server list; ActiveCanvas.Document switches what is visible
        server.PromoteDocument(_internalDocument);
        Grasshopper.Instances.ActiveCanvas.Document = _internalDocument;
    }

    // LLM RESPONSE ==================================================================

    /// <summary>
    /// Parses the raw LLM response and builds the cluster. Not yet implemented.
    /// </summary>
    /// <param name="rawResponse">The raw JSON string returned by the LLM.</param>
    public override void ApplyLlmResponse(string rawResponse)
    {
    }

    /// <summary>
    /// Returns null — cluster error reporting not yet implemented.
    /// </summary>
    /// <returns>null.</returns>
    public override string? GetFixMessage()
    {
        return null;
    }

    // IGH_DOCUMENT OWNER ====================================================================

    /// <summary>
    /// Called by the inner document when its contents change.
    /// Expires this component so its outputs are recalculated.
    /// </summary>
    /// <param name="document">The inner document that was modified.</param>
    public void DocumentModified(GH_Document document)
    {
        ExpireSolution(true);
    }

    /// <summary>
    /// Called by the inner document when it is closed (Save &amp; Close). Snapshots the
    /// current document state to XML before GH clears the document's objects.
    /// </summary>
    /// <param name="document">The inner document that was closed.</param>
    public void DocumentClosed(GH_Document document)
    {
        // Capture state before GH clears the document's objects.
        var archive = new GH_Archive();
        archive.AppendObject(_internalDocument, "ClusterDoc");
        _snapshotXml = archive.Serialize_Xml();
    }

    /// <summary>
    /// Returns the parent GH document that contains this component.
    /// </summary>
    /// <returns>The parent <see cref="GH_Document"/>.</returns>
    public GH_Document OwnerDocument()
    {
        return OnPingDocument();
    }

    // PRIVATE HELPERS ====================================================================

    /// <summary>
    /// Creates a new <see cref="GH_Document"/> with this component set as owner.
    /// </summary>
    /// <returns>A freshly initialised inner document.</returns>
    private GH_Document MakeFreshDocument()
    {
        var doc = new GH_Document();
        doc.Owner = this;
        doc.Nested = true;
        return doc;
    }

    // sanitizes param names to valid GH parameter names
    protected override string SanitizeParamName(string name)
    {
        // Replace any character that isn't alphanumeric, underscore, or space with underscore
        var clean = Regex.Replace(name, @"[^a-zA-Z0-9_ ]", "_");

        // Collapse runs of underscores/spaces and trim
        clean = Regex.Replace(clean, @"[ _]+", " ").Trim();

        if (string.IsNullOrEmpty(clean))
        {
            return "param";
        }

        return clean;
    }
}
