// Copyright (c) 2026 Physalia Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text.RegularExpressions;
using GH_IO.Serialization;
using Grasshopper.Kernel;
using Grasshopper.Kernel.Parameters;
using Grasshopper.Kernel.Special;
using Physalia.GH.Attributes;

namespace Physalia.GH.Components;

/// <summary>
/// The CLUSTER ZOOID component hosts a Grasshopper cluster generated by a paired COMPOSER.
/// Its input and output parameters are rebuilt dynamically from the LLM response.
/// </summary>
public class ClusterZooid : ZooidBase, IGH_DocumentOwner
{
    // FIELDS ==========================================================================================

    // The live inner document. Replaced with a fresh instance on each re-open so that
    // GH_Document.Read() always starts from a clean slate (avoids NRE from stale internal state
    // left by GH's close cycle on the previous instance).
    private GH_Document _internalDocument;

    // Snapshot of the inner document as XML. Captured in DocumentClosed before GH clears
    // the document's objects. Restored into a fresh document on next OpenEditor or SolveInstance.
    private string? _snapshotXml;

    // Maps outer input/output parameter InstanceGuid → inner hook InstanceGuid.
    // Rebuilt by SyncHooks() whenever parameters change or the inner document is restored.
    private Dictionary<Guid, Guid> _inputHookMap = new();
    private Dictionary<Guid, Guid> _outputHookMap = new();

    // Guards DocumentModified against re-entering ExpireSolution during our own solve cycle.
    private bool _solving;

    // Guards SyncOuterFromInner from running while SyncHooks() is pushing outer → inner,
    // preventing a re-entrant reverse sync.
    private bool _syncingHooks;

    // PROPERTIES =======================================================================================

    /// <summary>
    /// Gets the unique ID for this component. Do not change this ID after release.
    /// </summary>
    public override Guid ComponentGuid
        => new Guid("50F82419-28B2-4661-9677-C6B0D718CDC7");

    /// <summary>
    /// Gets the system prompt fragment describing the cluster format and JSON response schema.
    /// Combined with <see cref="Physalia.Core.Prompts.SystemPrompt.Preamble"/> by COMPOSER.
    /// </summary>
    public override string FormatPrompt => "Cluster format prompt — to be defined.";

    /// <summary>
    /// Gets the current state of this Zooid. Returns null until a response has been received.
    /// </summary>
    public override string? State => null;

    /// <summary>
    /// Gets a description of this Zooid's current inputs, outputs, and functionality.
    /// Returns null until a response has been received.
    /// </summary>
    public override string? ZooidDescription => null;

    // CONSTRUCTOR =======================================================================================

    /// <summary>
    /// Initializes a new instance of the <see cref="ClusterZooid"/> class.
    /// </summary>
    public ClusterZooid()
        : base(
            "ClusterZooid",
            "ClZ",
            "Generated Grasshopper Cluster",
            "Core")
    {
        _internalDocument = MakeFreshDocument();
    }

    // GH COMPONENT OVERRIDES ============================================================================================

    /// <summary>
    /// No fixed input parameters are registered; all inputs are added dynamically via
    /// <see cref="ApplyLlmResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The input parameter manager (unused).</param>
    protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
    {
    }

    /// <summary>
    /// No fixed output parameters are registered; all outputs are added dynamically via
    /// <see cref="ApplyLlmResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The output parameter manager (unused).</param>
    protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
    {
    }

    /// <summary>
    /// Pushes outer input data into the inner document's cluster input hooks,
    /// solves the inner document, then pulls results from the cluster output hooks
    /// back into this component's output parameters.
    /// </summary>
    /// <param name="DA">The DA object is used to retrieve from inputs and store in outputs.</param>
    protected override void SolveInstance(IGH_DataAccess DA)
    {
        // Let the inner document manage all data tree logic; receive everything in one pass.
        DA.DisableGapLogic();
        if (DA.Iteration > 0)
            return;

        _solving = true;
        try
        {
            EnsureLiveDocument();

            // 1. Push outer inputs → inner input hooks
            for (int i = 0; i < Params.Input.Count; i++)
            {
                IGH_Param outer = Params.Input[i];
                if (!_inputHookMap.TryGetValue(outer.InstanceGuid, out Guid hookGuid))
                    continue;

                IGH_Param? hook = _internalDocument.FindParameter(hookGuid);
                if (hook == null)
                    continue;

                hook.ClearData();
                hook.ExpireSolution(false);
                if (outer.VolatileData?.PathCount > 0)
                    hook.AddVolatileDataTree(outer.VolatileData);
            }

            // 2. Solve the inner document
            _internalDocument.Enabled = true;
            _internalDocument.NewSolution(false);
            _internalDocument.Enabled = false;

            // 3. Pull inner output hooks → outer output parameters
            for (int k = 0; k < Params.Output.Count; k++)
            {
                IGH_Param outer = Params.Output[k];
                if (!_outputHookMap.TryGetValue(outer.InstanceGuid, out Guid hookGuid))
                    continue;

                IGH_Param? hook = _internalDocument.FindParameter(hookGuid);
                if (hook == null)
                    continue;

                outer.VolatileData.Clear();
                outer.AddVolatileDataTree(hook.VolatileData);
            }
        }
        finally
        {
            _solving = false;
        }
    }

    /// <summary>
    /// Assigns the custom <see cref="ZooidAttrib"/> attribute class to this component.
    /// </summary>
    public override void CreateAttributes() => m_attributes = new ZooidAttrib(this);

    /// <summary>
    /// Re-subscribes rename listeners for all user-defined parameters after the component is loaded into a document.
    /// </summary>
    /// <param name="document">The document this component was added to.</param>
    public override void AddedToDocument(GH_Document document)
    {
        base.AddedToDocument(document);
        SubscribeUserParamEvents();
    }

    /// <summary>
    /// Removes the internal document from the GH document server when this component is deleted.
    /// </summary>
    /// <param name="document">The document this component was removed from.</param>
    public override void RemovedFromDocument(GH_Document document)
    {
        var server = Grasshopper.Instances.DocumentServer;
        if (server.Contains(_internalDocument))
            server.SafeRemoveDocument(_internalDocument);

        base.RemovedFromDocument(document);
    }

    /// <summary>
    /// Extends the base parameter maintenance to keep inner document hooks in sync
    /// whenever the outer parameter list changes.
    /// </summary>
    public override void VariableParameterMaintenance()
    {
        base.VariableParameterMaintenance();

        // Only sync while the inner document is live; if a snapshot is pending the
        // sync will happen automatically when EnsureLiveDocument is next called.
        if (_snapshotXml == null)
            SyncHooks();
    }

    // SERIALIZATION ==========================================================================

    /// <summary>
    /// Serializes the cluster state so it survives save and reload.
    /// Uses <see cref="_snapshotXml"/> as the source of truth when the inner document
    /// has been cleared by GH (after Save and Close), falling back to the live document.
    /// </summary>
    /// <param name="writer">The GH_IWriter to write to.</param>
    /// <returns>true.</returns>
    public override bool Write(GH_IWriter writer)
    {
        string xml;
        if (_snapshotXml != null)
        {
            xml = _snapshotXml;
        }
        else
        {
            var archive = new GH_Archive();
            archive.AppendObject(_internalDocument, "ClusterDoc");
            xml = archive.Serialize_Xml();
        }

        writer.SetString("InternalDocumentXml", xml);
        return base.Write(writer);
    }

    /// <summary>
    /// Deserialises the cluster state. Stores the XML in <see cref="_snapshotXml"/>
    /// so the inner document can be restored into a fresh instance on first use.
    /// </summary>
    /// <param name="reader">The GH_IReader to read from.</param>
    /// <returns>true.</returns>
    public override bool Read(GH_IReader reader)
    {
        if (reader.ItemExists("InternalDocumentXml"))
            _snapshotXml = reader.GetString("InternalDocumentXml");

        return base.Read(reader);
    }

    // EDITOR ========================================================================

    /// <summary>
    /// Opens the internal Grasshopper document in the GH editor, the same way a native
    /// cluster component does when double-clicked. Restores from snapshot if needed,
    /// then switches the active canvas to show the inner document.
    /// </summary>
    public override void OpenEditor()
    {
        EnsureLiveDocument();

        var server = Grasshopper.Instances.DocumentServer;
        _internalDocument.Enabled = true;
        server.PromoteDocument(_internalDocument);
        Grasshopper.Instances.ActiveCanvas.Document = _internalDocument;
    }

    // LLM RESPONSE ==================================================================

    /// <summary>
    /// Parses the raw LLM response and builds the cluster. Not yet implemented.
    /// </summary>
    /// <param name="rawResponse">The raw JSON string returned by the LLM.</param>
    public override void ApplyLlmResponse(string rawResponse)
    {
        // TODO: parse response JSON and rebuild params via ParamBuilder.Rebuild().
        EnsureLiveDocument();
        SyncHooks();
        ExpireSolution(true);
    }

    /// <summary>
    /// Returns null — cluster error reporting not yet implemented.
    /// </summary>
    /// <returns>null.</returns>
    public override string? GetFixMessage() => null;

    // IGH_DOCUMENT OWNER ====================================================================

    /// <summary>
    /// Called by the inner document when its contents change.
    /// Expires this component so its outputs are recalculated, and syncs any newly placed
    /// inner hooks back to outer params — both only outside of our own solve/sync cycles
    /// to prevent re-entrance.
    /// </summary>
    /// <param name="document">The inner document that was modified.</param>
    public void DocumentModified(GH_Document document)
    {
        if (!_solving)
            ExpireSolution(true);

        if (!_solving && !_syncingHooks && _snapshotXml == null)
            SyncOuterFromInner();
    }

    /// <summary>
    /// Called by the inner document when it is closed (Save &amp; Close). Snapshots the
    /// current document state to XML before GH clears the document's objects.
    /// </summary>
    /// <param name="document">The inner document that was closed.</param>
    public void DocumentClosed(GH_Document document)
    {
        var archive = new GH_Archive();
        archive.AppendObject(_internalDocument, "ClusterDoc");
        _snapshotXml = archive.Serialize_Xml();

        // Hook maps are keyed by current outer-param GUIDs and will be rebuilt from
        // the restored snapshot by SyncHooks() the next time EnsureLiveDocument() runs.
        _inputHookMap.Clear();
        _outputHookMap.Clear();
    }

    /// <summary>
    /// Returns the parent GH document that contains this component.
    /// </summary>
    /// <returns>The parent <see cref="GH_Document"/>.</returns>
    public GH_Document OwnerDocument() => OnPingDocument();

    // PRIVATE HELPERS ====================================================================

    /// <summary>
    /// Creates a new <see cref="GH_Document"/> with this component set as owner.
    /// </summary>
    private GH_Document MakeFreshDocument()
    {
        return new GH_Document
        {
            Owner = this,
            Nested = true,
        };
    }

    /// <summary>
    /// Ensures <see cref="_internalDocument"/> is registered on the GH document server and
    /// its objects are fully initialised. If a snapshot is pending it is restored into a fresh
    /// document first. After restoring, <see cref="SyncHooks"/> reconciles the cluster hooks
    /// with the current outer parameter list.
    /// </summary>
    private void EnsureLiveDocument()
    {
        var server = Grasshopper.Instances.DocumentServer;

        // Fast path: document is already live on the server with no snapshot pending.
        if (_snapshotXml == null && server.Contains(_internalDocument))
            return;

        // Remove the stale document from the server if it is still registered
        // (e.g. an immediate re-open before GH had a chance to remove it).
        if (server.Contains(_internalDocument))
        {
            _internalDocument.IsModified = false;
            server.SafeRemoveDocument(_internalDocument);
        }

        // Always start from a fresh document — GH_Document.Read() must start from a clean slate.
        _internalDocument = MakeFreshDocument();

        // Add to server BEFORE restoring snapshot — AddDocument sets up RhinoDocument
        // on the document, which GH_Document.Read() accesses internally and NREs without.
        server.AddDocument(_internalDocument);
        _internalDocument.Owner = this;
        _internalDocument.Nested = true;

        if (_snapshotXml != null)
        {
            var archive = new GH_Archive();
            if (archive.Deserialize_Xml(_snapshotXml))
            {
                // Suppress events during Read() to avoid cascading solution cycles.
                _internalDocument.RaiseEvents = false;
                archive.ExtractObject(_internalDocument, "ClusterDoc");
                _internalDocument.RaiseEvents = true;
            }

            _snapshotXml = null;
        }

        // Re-assert after restore in case Read() cleared them.
        _internalDocument.Owner = this;
        _internalDocument.Nested = true;

        SyncHooks();
    }

    /// <summary>
    /// Synchronises the inner document's <see cref="GH_ClusterInputHook"/> and
    /// <see cref="GH_ClusterOutputHook"/> instances to match the current outer parameter list.
    /// Hooks are matched by NickName so existing internal wiring is preserved across rebuilds.
    /// New hooks are created for new outer params; orphaned hooks are removed.
    /// </summary>
    private void SyncHooks()
    {
        if (_internalDocument == null)
            return;

        // Suppress document events and guard against re-entrant reverse sync while
        // pushing outer → inner changes.
        _syncingHooks = true;
        bool wasRaisingEvents = _internalDocument.RaiseEvents;
        _internalDocument.RaiseEvents = false;
        try
        {
            SyncHookSide(
                Params.Input,
                _internalDocument.ClusterInputHooks(),
                ref _inputHookMap,
                isInput: true);

            SyncHookSide(
                Params.Output,
                _internalDocument.ClusterOutputHooks(),
                ref _outputHookMap,
                isInput: false);
        }
        finally
        {
            _internalDocument.RaiseEvents = wasRaisingEvents;
            _syncingHooks = false;
        }
    }

    /// <summary>
    /// Reverse-syncs outer params from the inner document's hooks. Called from
    /// <see cref="DocumentModified"/> when the user places a hook on the inner canvas.
    /// Creates an outer param for any hook that has no corresponding outer param by NickName.
    /// </summary>
    private void SyncOuterFromInner()
    {
        var inputHooks = _internalDocument.ClusterInputHooks() ?? Array.Empty<IGH_Param>();
        var outputHooks = _internalDocument.ClusterOutputHooks() ?? Array.Empty<IGH_Param>();

        var outerInputNicks = new HashSet<string>(Params.Input.Select(p => p.NickName));
        var outerOutputNicks = new HashSet<string>(Params.Output.Select(p => p.NickName));

        bool changed = false;

        foreach (var hook in inputHooks)
        {
            if (outerInputNicks.Contains(hook.NickName))
                continue;

            var param = new Param_GenericObject
            {
                Name = hook.NickName,
                NickName = hook.NickName,
                Description = "user defined parameter",
                Optional = true,
            };
            Params.RegisterInputParam(param);
            _inputHookMap[param.InstanceGuid] = hook.InstanceGuid;
            changed = true;
        }

        foreach (var hook in outputHooks)
        {
            if (outerOutputNicks.Contains(hook.NickName))
                continue;

            var param = new Param_GenericObject
            {
                Name = hook.NickName,
                NickName = hook.NickName,
                Description = "user defined parameter",
                Optional = true,
            };
            Params.RegisterOutputParam(param);
            _outputHookMap[param.InstanceGuid] = hook.InstanceGuid;
            changed = true;
        }

        if (changed)
        {
            Params.OnParametersChanged();
            ExpireSolution(true);
        }
    }

    // Syncs one side (inputs or outputs) of the hook mapping.
    // existingHooks is GH_ClusterInputHook[] or GH_ClusterOutputHook[]; both implement IGH_Param.
    private void SyncHookSide(
        List<IGH_Param> outerParams,
        IGH_Param[]? existingHooks,
        ref Dictionary<Guid, Guid> hookMap,
        bool isInput)
    {
        var byNick = (existingHooks ?? Array.Empty<IGH_Param>()).ToDictionary(h => h.NickName);
        var newMap = new Dictionary<Guid, Guid>(outerParams.Count);
        var validNicks = new HashSet<string>(outerParams.Select(p => p.NickName));

        for (int i = 0; i < outerParams.Count; i++)
        {
            IGH_Param outer = outerParams[i];

            if (byNick.TryGetValue(outer.NickName, out IGH_Param? existingHook))
            {
                // Set Custom* overrides so the hook ignores source/recipient name inheritance.
                var existingClusterHook = (GH_ClusterHook)existingHook;
                existingClusterHook.CustomName = outer.NickName;
                existingClusterHook.CustomNickName = outer.NickName;
                newMap[outer.InstanceGuid] = existingHook.InstanceGuid;
            }
            else
            {
                // Create a new hook and place it on the inner canvas.
                IGH_Param newHook = isInput
                    ? (IGH_Param)new GH_ClusterInputHook()
                    : (IGH_Param)new GH_ClusterOutputHook();

                // Set Custom* overrides — plain Name/NickName setters write to the base backing
                // field but the getter walks Sources/Recipients once the hook is wired, so it
                // would silently replace our label. CustomName/CustomNickName take priority.
                var clusterHook = (GH_ClusterHook)newHook;
                clusterHook.CustomName = outer.NickName;
                clusterHook.CustomNickName = outer.NickName;
                newHook.CreateAttributes();
                newHook.Attributes.Pivot = new PointF(isInput ? 50f : 500f, 100f + i * 60f);

                _internalDocument.AddObject(newHook, update: false);
                newMap[outer.InstanceGuid] = newHook.InstanceGuid;
            }
        }

        // Remove hooks whose corresponding outer param has been removed.
        foreach (var (nick, hook) in byNick)
        {
            if (!validNicks.Contains(nick))
                _internalDocument.RemoveObject(hook, false);
        }

        hookMap = newMap;
    }

    /// <summary>
    /// Syncs inner document hooks and expires the solution when a user renames an outer param.
    /// </summary>
    /// <param name="p">The renamed parameter.</param>
    protected override void AfterParamNickNameChanged(IGH_Param p)
    {
        if (_snapshotXml == null)
            SyncHooks();

        ExpireSolution(true);
    }

    // Sanitizes param names to valid GH parameter names.
    protected override string SanitizeParamName(string name)
    {
        // Replace any character that isn't alphanumeric, underscore, or space with underscore
        var clean = Regex.Replace(name, @"[^a-zA-Z0-9_ ]", "_");

        // Collapse runs of underscores/spaces and trim
        clean = Regex.Replace(clean, @"[ _]+", " ").Trim();

        if (string.IsNullOrEmpty(clean))
            return "param";

        return clean;
    }
}
