// Copyright (c) 2026 Physalia Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.Json;
using GH_IO.Serialization;
using Grasshopper.Kernel;
using Grasshopper.Kernel.Parameters;
using Grasshopper.Kernel.Special;
using Grasshopper.Kernel.Types;
using Physalia.Core.Parsing;
using Physalia.GH.Attributes;
using Physalia.GH.Helpers;

namespace Physalia.GH.Components;

/// <summary>
/// The CLUSTER ZOOID component hosts a Grasshopper cluster generated by a paired COMPOSER.
/// Its input and output parameters are rebuilt dynamically from the LLM response.
/// </summary>
public class ClusterZooid : ZooidBase, IGH_DocumentOwner
{
    // FIELDS ==========================================================================================

    // The live inner document. Replaced with a fresh instance on each re-open so that
    // GH_Document.Read() always starts from a clean slate (avoids NRE from stale internal state
    // left by GH's close cycle on the previous instance).
    private GH_Document _internalDocument;

    // Snapshot of the inner document as XML. Captured in DocumentClosed before GH clears
    // the document's objects. Restored into a fresh document on next OpenEditor or SolveInstance.
    private string? _snapshotXml;

    // Maps outer input/output parameter InstanceGuid → inner hook InstanceGuid.
    // Rebuilt by SyncHooks() whenever parameters change or the inner document is restored.
    private Dictionary<Guid, Guid> _inputHookMap = new();
    private Dictionary<Guid, Guid> _outputHookMap = new();

    // Guards DocumentModified against re-entering ExpireSolution during our own solve cycle.
    private bool _solving;

    // Guards SyncOuterFromInner from running while SyncHooks() is pushing outer → inner,
    // preventing a re-entrant reverse sync.
    private bool _syncingHooks;

    // Parsed response from the last LLM call; null until a response has been received.
    private ClusterResponse? _lastResponse;

    // Component-not-found and wire-resolution errors from the last ApplyLlmResponse call.
    // Reported by GetFixMessage() so the auto-fix loop can correct them.
    private List<string> _lastClusterErrors = new ();

    // Maps component id → (GH name, formatted input NickNames, formatted output NickNames).
    // Populated during BuildInnerDocument and appended to the fix prompt so the LLM has
    // an exact NickName reference for every component it placed.
    private Dictionary<string, (string Name, string Inputs, string Outputs)> _componentReference = new ();

    // PROPERTIES =======================================================================================

    /// <summary>
    /// Gets the unique ID for this component. Do not change this ID after release.
    /// </summary>
    public override Guid ComponentGuid
        => new Guid("50F82419-28B2-4661-9677-C6B0D718CDC7");

    /// <summary>
    /// Gets the system prompt fragment describing the cluster format and JSON response schema.
    /// Combined with <see cref="Physalia.Core.Prompts.SystemPrompt.Preamble"/> by COMPOSER.
    /// The installed plugin list is injected at access time so it reflects the user's current environment.
    /// </summary>
    public override string FormatPrompt
    {
        get
        {
            var plugins = GetInstalledPluginNames();
            var pluginLine = plugins.Count > 0
                ? $"Installed GH plugins: {string.Join(", ", plugins)}"
                : "No third-party plugins are installed.";
            return _formatPromptTemplate.Replace("{PLUGIN_LINE}", pluginLine);
        }
    }

    // Template for FormatPrompt. {PLUGIN_LINE} is replaced at runtime with the actual plugin list.
    private static readonly string _formatPromptTemplate = """
        You generate Grasshopper cluster definitions as a JSON node graph.
        Each cluster has outer input/output parameters and an inner graph of GH components connected by wires.

        {PLUGIN_LINE}
        Only use standard Grasshopper components or components from the plugins listed above.
        Do not use components from plugins that are not listed.

        WIRE NOTATION:
        - "input.<name>"    connects from a cluster input hook named <name>
        - "<id>.<nickName>" connects from component <id>'s output parameter <nickName>
        - "<id>.output"     connects from a Number, Integer, or Boolean parameter component

        RESPONSE FORMAT:
        You MUST respond with ONLY a JSON object (no markdown fences, no preamble) matching
        this exact schema:

        {
          "statusMessage": "<one short sentence describing what you built>",
          "inputs": [
            {
              "name": "<param_name>",
              "prettyName": "<Human Readable Name>",
              "tooltip": "<short description>",
              "typeHint": "<GH type hint>",
              "access": "item|list|tree",
              "optional": false
            }
          ],
          "outputs": [
            {
              "name": "<param_name>",
              "prettyName": "<Human Readable Name>",
              "tooltip": "<short description>",
              "from": "<wire source>"
            }
          ],
          "components": [
            {
              "id": "<unique id, e.g. c1>",
              "type": "<GH component Name>",
              "nickname": "<optional display label>",
              "inputs": {
                "<inputNickName>": "<wire source>"
              }
            }
          ]
        }

        VALID TYPE HINTS (use these exact strings):
        - Primitives: "Number", "Integer", "Boolean", "Text"
        - Geometry: "Point", "Vector", "Plane", "Line", "Circle", "Arc",
          "Curve", "Surface", "Brep", "Mesh", "Geometry", "Box",
          "Transform", "Interval"
        - Other: "Colour"

        ACCESS MODES:
        - "item": single value per iteration (default)
        - "list": a list of values
        - "tree": a data tree

        IMPORTANT:
        - Component "type" must be the exact GH component Name (e.g. "Addition", "Move", "Bounding Box").
        - Use the component's standard output parameter NickName in wire sources (e.g. "c1.R" for Addition's Result).
        - Always include "statusMessage" as the first key in the JSON object.
        - Do NOT use scripting components of any kind (Python Script, C# Script, VB Script, or any script/code component).
        - Add Panel components (type: "Panel", inputs: {}) to annotate important steps or groups.
          Set nickname to the description text. Set annotates to the id of the component being described.
          Panels are purely decorative — they cannot be wired from.
        - For all static constant values use a parameter component, NOT a Panel:
            - Float/decimal constant → type "Number",  nickname: the value e.g. "3.14"
            - Integer constant       → type "Integer", nickname: the value e.g. "10"
            - Boolean constant       → type "Boolean", nickname: "true" or "false"
          Wire from these using "<id>.output".
        - Respond with ONLY the JSON object. No other text.
        """;

    /// <summary>
    /// Gets the current state of this Zooid. Returns null until a response has been received.
    /// </summary>
    public override string? State => _lastResponse?.StatusMessage;

    /// <summary>
    /// Gets a description of this Zooid's current inputs, outputs, and functionality.
    /// Returns null until a response has been received.
    /// </summary>
    public override string? ZooidDescription => _lastResponse?.StatusMessage;

    // CONSTRUCTOR =======================================================================================

    /// <summary>
    /// Initializes a new instance of the <see cref="ClusterZooid"/> class.
    /// </summary>
    public ClusterZooid()
        : base(
            "ClusterZooid",
            "ClZ",
            "Generated Grasshopper Cluster",
            "Core")
    {
        IconPath = "Physalia.GH.Resources.microbe.png";
        _internalDocument = MakeFreshDocument();
    }

    // GH COMPONENT OVERRIDES ============================================================================================

    /// <summary>
    /// No fixed input parameters are registered; all inputs are added dynamically via
    /// <see cref="ApplyLlmResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The input parameter manager (unused).</param>
    protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
    {
    }

    /// <summary>
    /// No fixed output parameters are registered; all outputs are added dynamically via
    /// <see cref="ApplyLlmResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The output parameter manager (unused).</param>
    protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
    {
    }

    /// <summary>
    /// Pushes outer input data into the inner document's cluster input hooks,
    /// solves the inner document, then pulls results from the cluster output hooks
    /// back into this component's output parameters.
    /// </summary>
    /// <param name="DA">The DA object is used to retrieve from inputs and store in outputs.</param>
    protected override void SolveInstance(IGH_DataAccess DA)
    {
        // Let the inner document manage all data tree logic; receive everything in one pass.
        DA.DisableGapLogic();
        if (DA.Iteration > 0)
            return;

        _solving = true;
        try
        {
            EnsureLiveDocument();

            // 1. Push outer inputs → inner input hooks
            for (int i = 0; i < Params.Input.Count; i++)
            {
                IGH_Param outer = Params.Input[i];
                if (!_inputHookMap.TryGetValue(outer.InstanceGuid, out Guid hookGuid))
                    continue;

                IGH_Param? hook = _internalDocument.FindParameter(hookGuid);
                if (hook == null)
                    continue;

                hook.ClearData();
                hook.ExpireSolution(false);
                if (outer.VolatileData?.PathCount > 0)
                    hook.AddVolatileDataTree(outer.VolatileData);
            }

            // 2. Solve the inner document
            _internalDocument.Enabled = true;
            _internalDocument.NewSolution(false);
            _internalDocument.Enabled = false;

            // 3. Pull inner output hooks → outer output parameters
            for (int k = 0; k < Params.Output.Count; k++)
            {
                IGH_Param outer = Params.Output[k];
                if (!_outputHookMap.TryGetValue(outer.InstanceGuid, out Guid hookGuid))
                    continue;

                IGH_Param? hook = _internalDocument.FindParameter(hookGuid);
                if (hook == null)
                    continue;

                outer.VolatileData.Clear();
                outer.AddVolatileDataTree(hook.VolatileData);
            }
        }
        finally
        {
            _solving = false;
        }
    }

    /// <summary>
    /// Assigns the custom <see cref="ZooidAttrib"/> attribute class to this component.
    /// </summary>
    public override void CreateAttributes() => m_attributes = new ZooidAttrib(this);

    /// <summary>
    /// Re-subscribes rename listeners for all user-defined parameters after the component is loaded into a document.
    /// </summary>
    /// <param name="document">The document this component was added to.</param>
    public override void AddedToDocument(GH_Document document)
    {
        base.AddedToDocument(document);
        SubscribeUserParamEvents();
    }

    /// <summary>
    /// Removes the internal document from the GH document server when this component is deleted.
    /// </summary>
    /// <param name="document">The document this component was removed from.</param>
    public override void RemovedFromDocument(GH_Document document)
    {
        var server = Grasshopper.Instances.DocumentServer;
        if (server.Contains(_internalDocument))
            server.SafeRemoveDocument(_internalDocument);

        base.RemovedFromDocument(document);
    }

    /// <summary>
    /// Extends the base parameter maintenance to keep inner document hooks in sync
    /// whenever the outer parameter list changes.
    /// </summary>
    public override void VariableParameterMaintenance()
    {
        base.VariableParameterMaintenance();

        // Only sync while the inner document is live; if a snapshot is pending the
        // sync will happen automatically when EnsureLiveDocument is next called.
        if (_snapshotXml == null)
            SyncHooks();
    }

    // SERIALIZATION ==========================================================================

    /// <summary>
    /// Serializes the cluster state so it survives save and reload.
    /// Uses <see cref="_snapshotXml"/> as the source of truth when the inner document
    /// has been cleared by GH (after Save and Close), falling back to the live document.
    /// </summary>
    /// <param name="writer">The GH_IWriter to write to.</param>
    /// <returns>true.</returns>
    public override bool Write(GH_IWriter writer)
    {
        string xml;
        if (_snapshotXml != null)
        {
            xml = _snapshotXml;
        }
        else
        {
            var archive = new GH_Archive();
            archive.AppendObject(_internalDocument, "ClusterDoc");
            xml = archive.Serialize_Xml();
        }

        writer.SetString("InternalDocumentXml", xml);

        if (_lastResponse != null)
            writer.SetString("ClusterResponseJson", JsonSerializer.Serialize(_lastResponse));

        return base.Write(writer);
    }

    /// <summary>
    /// Deserialises the cluster state. Stores the XML in <see cref="_snapshotXml"/>
    /// so the inner document can be restored into a fresh instance on first use.
    /// </summary>
    /// <param name="reader">The GH_IReader to read from.</param>
    /// <returns>true.</returns>
    public override bool Read(GH_IReader reader)
    {
        if (reader.ItemExists("InternalDocumentXml"))
            _snapshotXml = reader.GetString("InternalDocumentXml");

        string responseJson = string.Empty;
        if (reader.TryGetString("ClusterResponseJson", ref responseJson))
            _lastResponse = JsonSerializer.Deserialize<ClusterResponse>(responseJson);

        return base.Read(reader);
    }

    // EDITOR ========================================================================

    /// <summary>
    /// Opens the internal Grasshopper document in the GH editor, the same way a native
    /// cluster component does when double-clicked. Restores from snapshot if needed,
    /// then switches the active canvas to show the inner document.
    /// </summary>
    public override void OpenEditor()
    {
        EnsureLiveDocument();

        var server = Grasshopper.Instances.DocumentServer;
        _internalDocument.Enabled = true;
        server.PromoteDocument(_internalDocument);
        Grasshopper.Instances.ActiveCanvas.Document = _internalDocument;
    }

    // LLM RESPONSE ==================================================================

    /// <summary>
    /// Parses the raw LLM response, rebuilds the outer parameters, and reconstructs the inner
    /// document with the described components and wires.
    /// </summary>
    /// <param name="rawResponse">The raw JSON string returned by the LLM.</param>
    public override void ApplyLlmResponse(string rawResponse)
    {
        _lastResponse = ResponseParser.ParseCluster(rawResponse);
        LastStatusMessage = _lastResponse.StatusMessage;
        _lastClusterErrors.Clear();

        var outputParamDefs = _lastResponse.Outputs
            .Select(o => new ParamDefinition { Name = o.Name, PrettyName = o.PrettyName, Tooltip = o.Tooltip })
            .ToList();

        EnsureLiveDocument();

        // Suppress inner document events for the entire rebuild to prevent DocumentModified
        // firing mid-rebuild, which would trigger SyncOuterFromInner while hooks are wired
        // and their NickName getters return the connected component's param name rather than
        // CustomNickName, causing spurious outer params and a corrupted hook map.
        _internalDocument.RaiseEvents = false;
        try
        {
            ClearInnerDocument();

            // Only rebuild outer params on the first response. Once params are established
            // the LLM is instructed never to add, remove, or rename them, so subsequent
            // calls (including autofix) must not alter the outer parameter list.
            if (Params.Input.Count == 0 && Params.Output.Count == 0)
                ParamBuilder.Rebuild(this, _lastResponse.Inputs, outputParamDefs);

            // Create hooks before BuildInnerDocument wires to them. OnParametersChanged inside
            // ParamBuilder.Rebuild may not call VariableParameterMaintenance synchronously.
            SyncHooks();

            BuildInnerDocument(_lastResponse);
        }
        finally
        {
            _internalDocument.RaiseEvents = true;
        }

        ExpireSolution(true);
    }

    /// <summary>
    /// Builds a fix prompt from any component-not-found or wiring errors recorded during the
    /// last <see cref="ApplyLlmResponse"/> call. Returns null if there are no errors.
    /// </summary>
    /// <returns>A formatted error message, or null if there are no errors.</returns>
    public override string? GetFixMessage()
    {
        if (_lastClusterErrors.Count == 0)
            return null;

        var sb = new StringBuilder();
        sb.AppendLine("The cluster has errors. Return a corrected JSON response in the same format.");
        sb.AppendLine();
        foreach (var err in _lastClusterErrors)
            sb.AppendLine($"  - {err}");

        if (_componentReference.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("Exact NickNames for all placed components (use these precisely for wiring):");
            foreach (var (id, info) in _componentReference)
                sb.AppendLine($"  {id} ({info.Name}): inputs [{info.Inputs}]  outputs [{info.Outputs}]");
        }

        return sb.ToString();
    }

    // IGH_DOCUMENT OWNER ====================================================================

    /// <summary>
    /// Called by the inner document when its contents change.
    /// Expires this component so its outputs are recalculated, and syncs any newly placed
    /// inner hooks back to outer params — both only outside of our own solve/sync cycles
    /// to prevent re-entrance.
    /// </summary>
    /// <param name="document">The inner document that was modified.</param>
    public void DocumentModified(GH_Document document)
    {
        if (!_solving)
            ExpireSolution(true);

        if (!_solving && !_syncingHooks && _snapshotXml == null)
            SyncOuterFromInner();
    }

    /// <summary>
    /// Called by the inner document when it is closed (Save &amp; Close). Snapshots the
    /// current document state to XML before GH clears the document's objects.
    /// </summary>
    /// <param name="document">The inner document that was closed.</param>
    public void DocumentClosed(GH_Document document)
    {
        var archive = new GH_Archive();
        archive.AppendObject(_internalDocument, "ClusterDoc");
        _snapshotXml = archive.Serialize_Xml();

        // Hook maps are keyed by current outer-param GUIDs and will be rebuilt from
        // the restored snapshot by SyncHooks() the next time EnsureLiveDocument() runs.
        _inputHookMap.Clear();
        _outputHookMap.Clear();
    }

    /// <summary>
    /// Returns the parent GH document that contains this component.
    /// </summary>
    /// <returns>The parent <see cref="GH_Document"/>.</returns>
    public GH_Document OwnerDocument() => OnPingDocument();

    // PRIVATE HELPERS ====================================================================

    /// <summary>
    /// Creates a new <see cref="GH_Document"/> with this component set as owner.
    /// </summary>
    private GH_Document MakeFreshDocument()
    {
        return new GH_Document
        {
            Owner = this,
            Nested = true,
        };
    }

    /// <summary>
    /// Ensures <see cref="_internalDocument"/> is registered on the GH document server and
    /// its objects are fully initialised. If a snapshot is pending it is restored into a fresh
    /// document first. After restoring, <see cref="SyncHooks"/> reconciles the cluster hooks
    /// with the current outer parameter list.
    /// </summary>
    private void EnsureLiveDocument()
    {
        var server = Grasshopper.Instances.DocumentServer;

        // Fast path: document is already live on the server with no snapshot pending.
        if (_snapshotXml == null && server.Contains(_internalDocument))
            return;

        // Remove the stale document from the server if it is still registered
        // (e.g. an immediate re-open before GH had a chance to remove it).
        if (server.Contains(_internalDocument))
        {
            _internalDocument.IsModified = false;
            server.SafeRemoveDocument(_internalDocument);
        }

        // Always start from a fresh document — GH_Document.Read() must start from a clean slate.
        _internalDocument = MakeFreshDocument();

        // Add to server BEFORE restoring snapshot — AddDocument sets up RhinoDocument
        // on the document, which GH_Document.Read() accesses internally and NREs without.
        server.AddDocument(_internalDocument);
        _internalDocument.Owner = this;
        _internalDocument.Nested = true;

        if (_snapshotXml != null)
        {
            var archive = new GH_Archive();
            if (archive.Deserialize_Xml(_snapshotXml))
            {
                // Suppress events during Read() to avoid cascading solution cycles.
                _internalDocument.RaiseEvents = false;
                archive.ExtractObject(_internalDocument, "ClusterDoc");
                _internalDocument.RaiseEvents = true;
            }

            _snapshotXml = null;
        }

        // Re-assert after restore in case Read() cleared them.
        _internalDocument.Owner = this;
        _internalDocument.Nested = true;

        SyncHooks();
    }

    /// <summary>
    /// Synchronises the inner document's <see cref="GH_ClusterInputHook"/> and
    /// <see cref="GH_ClusterOutputHook"/> instances to match the current outer parameter list.
    /// Hooks are matched by NickName so existing internal wiring is preserved across rebuilds.
    /// New hooks are created for new outer params; orphaned hooks are removed.
    /// </summary>
    private void SyncHooks()
    {
        if (_internalDocument == null)
            return;

        // Suppress document events and guard against re-entrant reverse sync while
        // pushing outer → inner changes.
        _syncingHooks = true;
        bool wasRaisingEvents = _internalDocument.RaiseEvents;
        _internalDocument.RaiseEvents = false;
        try
        {
            SyncHookSide(
                Params.Input,
                _internalDocument.ClusterInputHooks(),
                ref _inputHookMap,
                isInput: true);

            SyncHookSide(
                Params.Output,
                _internalDocument.ClusterOutputHooks(),
                ref _outputHookMap,
                isInput: false);
        }
        finally
        {
            _internalDocument.RaiseEvents = wasRaisingEvents;
            _syncingHooks = false;
        }
    }

    /// <summary>
    /// Reverse-syncs outer params from the inner document's hooks. Called from
    /// <see cref="DocumentModified"/> when the user places a hook on the inner canvas.
    /// Creates an outer param for any hook that has no corresponding outer param by NickName.
    /// </summary>
    private void SyncOuterFromInner()
    {
        var inputHooks = _internalDocument.ClusterInputHooks() ?? Array.Empty<IGH_Param>();
        var outputHooks = _internalDocument.ClusterOutputHooks() ?? Array.Empty<IGH_Param>();

        var outerInputNicks = new HashSet<string>(Params.Input.Select(p => p.NickName));
        var outerOutputNicks = new HashSet<string>(Params.Output.Select(p => p.NickName));

        bool changed = false;

        foreach (var hook in inputHooks)
        {
            if (outerInputNicks.Contains(hook.NickName))
                continue;

            var param = new Param_GenericObject
            {
                Name = hook.NickName,
                NickName = hook.NickName,
                Description = "user defined parameter",
                Optional = true,
            };
            Params.RegisterInputParam(param);
            _inputHookMap[param.InstanceGuid] = hook.InstanceGuid;
            changed = true;
        }

        foreach (var hook in outputHooks)
        {
            if (outerOutputNicks.Contains(hook.NickName))
                continue;

            var param = new Param_GenericObject
            {
                Name = hook.NickName,
                NickName = hook.NickName,
                Description = "user defined parameter",
                Optional = true,
            };
            Params.RegisterOutputParam(param);
            _outputHookMap[param.InstanceGuid] = hook.InstanceGuid;
            changed = true;
        }

        if (changed)
        {
            Params.OnParametersChanged();
            ExpireSolution(true);
        }
    }

    // Syncs one side (inputs or outputs) of the hook mapping.
    // existingHooks is GH_ClusterInputHook[] or GH_ClusterOutputHook[]; both implement IGH_Param.
    private void SyncHookSide(
        List<IGH_Param> outerParams,
        IGH_Param[]? existingHooks,
        ref Dictionary<Guid, Guid> hookMap,
        bool isInput)
    {
        var hooks = existingHooks ?? Array.Empty<IGH_Param>();

        // GUID map: used as the primary lookup. Survives post-wiring NickName changes because
        // GH_ClusterHook.NickName walks sources/recipients once wired, returning the connected
        // component's param name instead of our CustomNickName — making NickName-only matching
        // unreliable after BuildInnerDocument has run.
        var byGuid = hooks.ToDictionary(h => h.InstanceGuid);

        // NickName map: fallback for snapshot restoration, where all hook GUIDs are new
        // (fresh document) and the existing hookMap is empty.
        var byNick = new Dictionary<string, IGH_Param>(StringComparer.Ordinal);
        foreach (var h in hooks)
            byNick.TryAdd(h.NickName, h);

        var newMap = new Dictionary<Guid, Guid>(outerParams.Count);
        var usedGuids = new HashSet<Guid>();

        for (int i = 0; i < outerParams.Count; i++)
        {
            IGH_Param outer = outerParams[i];

            // Primary: look up by the GUID we recorded the last time this outer param was synced.
            IGH_Param? existingHook = null;
            if (hookMap.TryGetValue(outer.InstanceGuid, out Guid knownGuid))
                byGuid.TryGetValue(knownGuid, out existingHook);

            // Fallback: NickName match (handles snapshot restore where GUIDs are all new).
            if (existingHook == null)
                byNick.TryGetValue(outer.NickName, out existingHook);

            if (existingHook != null)
            {
                // Re-assert Custom* overrides so the hook ignores source/recipient name inheritance.
                var existingClusterHook = (GH_ClusterHook)existingHook;
                existingClusterHook.CustomName = outer.NickName;
                existingClusterHook.CustomNickName = outer.NickName;
                newMap[outer.InstanceGuid] = existingHook.InstanceGuid;
                usedGuids.Add(existingHook.InstanceGuid);
            }
            else
            {
                // Create a new hook and place it on the inner canvas.
                IGH_Param newHook = isInput
                    ? (IGH_Param)new GH_ClusterInputHook()
                    : (IGH_Param)new GH_ClusterOutputHook();

                var clusterHook = (GH_ClusterHook)newHook;
                clusterHook.CustomName = outer.NickName;
                clusterHook.CustomNickName = outer.NickName;
                newHook.CreateAttributes();
                newHook.Attributes.Pivot = new PointF(isInput ? 50f : 500f, 100f + i * 60f);

                _internalDocument.AddObject(newHook, update: false);
                newMap[outer.InstanceGuid] = newHook.InstanceGuid;
                usedGuids.Add(newHook.InstanceGuid);
            }
        }

        // Remove hooks that are no longer needed (not matched to any current outer param).
        // Use GUID identity rather than NickName to avoid false positives from wired NickName drift.
        foreach (var hook in hooks)
        {
            if (!usedGuids.Contains(hook.InstanceGuid))
                _internalDocument.RemoveObject(hook, false);
        }

        hookMap = newMap;
    }

    /// <summary>
    /// Syncs inner document hooks and expires the solution when a user renames an outer param.
    /// </summary>
    /// <param name="p">The renamed parameter.</param>
    protected override void AfterParamNickNameChanged(IGH_Param p)
    {
        if (_snapshotXml == null)
            SyncHooks();

        ExpireSolution(true);
    }

    // Removes all objects from the inner document with events suppressed.
    private void ClearInnerDocument()
    {
        bool wasRaisingEvents = _internalDocument.RaiseEvents;
        _internalDocument.RaiseEvents = false;
        try
        {
            foreach (var obj in _internalDocument.Objects.ToList())
                _internalDocument.RemoveObject(obj, false);

            _inputHookMap.Clear();
            _outputHookMap.Clear();
        }
        finally
        {
            _internalDocument.RaiseEvents = wasRaisingEvents;
        }
    }

    // Places GH components into the inner document and wires them according to the LLM response.
    // Unresolvable component types and broken wire sources are recorded in _lastClusterErrors.
    private void BuildInnerDocument(ClusterResponse response)
    {
        var byId = new Dictionary<string, IGH_Component>(StringComparer.OrdinalIgnoreCase);
        var paramById = new Dictionary<string, IGH_Param>(StringComparer.OrdinalIgnoreCase);
        _componentReference.Clear();

        bool wasRaisingEvents = _internalDocument.RaiseEvents;
        _internalDocument.RaiseEvents = false;
        try
        {
            // Pre-resolve all proxies and separate into GH components and standalone params.
            var resolvedComponents = new List<(ClusterComponentDef Def, IGH_Component Comp)>();
            var resolvedParams = new List<(ClusterComponentDef Def, IGH_Param Param)>();

            foreach (var def in response.Components)
            {
                var proxy = Grasshopper.Instances.ComponentServer.FindObjectByName(def.Type, true, true);
                if (proxy == null)
                {
                    _lastClusterErrors.Add($"Component type not found: \"{def.Type}\"");
                    continue;
                }

                var obj = proxy.CreateInstance();

                if (obj is GH_Panel panel)
                {
                    if (!string.IsNullOrWhiteSpace(def.Nickname))
                        panel.UserText = def.Nickname;
                    resolvedParams.Add((def, panel));
                }
                else if (obj is IGH_Param param)
                {
                    SetParamValue(param, def.Nickname);
                    resolvedParams.Add((def, param));
                }
                else if (obj is IGH_Component comp)
                {
                    if (def.Nickname != null)
                        comp.NickName = def.Nickname;
                    resolvedComponents.Add((def, comp));
                }
                else
                {
                    _lastClusterErrors.Add($"\"{def.Type}\" is not a usable GH object");
                }
            }

            // Add IGH_Component objects to the document.
            // HierarchicalLayout.Apply will assign final positions after wiring is complete.
            foreach (var (def, comp) in resolvedComponents)
            {
                comp.CreateAttributes();
                _internalDocument.AddObject(comp, false);
                byId[def.Id] = comp;
                _componentReference[def.Id] = (
                    comp.Name,
                    string.Join(", ", comp.Params.Input.Select(p => p.NickName)),
                    string.Join(", ", comp.Params.Output.Select(p => p.NickName)));
            }

            // Add standalone param objects to the document.
            foreach (var (def, param) in resolvedParams)
            {
                param.CreateAttributes();
                _internalDocument.AddObject(param, false);
                paramById[def.Id] = param;
            }

            // Wire component inputs
            foreach (var def in response.Components)
            {
                if (!byId.TryGetValue(def.Id, out var comp))
                    continue;

                foreach (var (nickName, source) in def.Inputs)
                {
                    var targetParam = comp.Params.Input.FirstOrDefault(p => p.NickName == nickName)
                        ?? comp.Params.Input.FirstOrDefault(p => string.Equals(p.NickName, nickName, StringComparison.OrdinalIgnoreCase))
                        ?? comp.Params.Input.FirstOrDefault(p => string.Equals(p.Name, nickName, StringComparison.OrdinalIgnoreCase));
                    if (targetParam == null)
                    {
                        var available = string.Join(", ", comp.Params.Input.Select(p => p.NickName));
                        _lastClusterErrors.Add($"Component \"{def.Id}\" ({def.Type}) has no input \"{nickName}\". Available: [{available}]");
                        continue;
                    }

                    var sourceParam = ResolveSource(source, byId, paramById);
                    if (sourceParam == null)
                    {
                        int srcDot = source.IndexOf('.');
                        string srcId = srcDot >= 0 ? source[..srcDot] : source;
                        if (byId.TryGetValue(srcId, out var srcComp))
                        {
                            var available = string.Join(", ", srcComp.Params.Output.Select(p => p.NickName));
                            _lastClusterErrors.Add($"Wire source \"{source}\" not found. Component \"{srcId}\" ({srcComp.Name}) has outputs: [{available}]");
                        }
                        else
                        {
                            _lastClusterErrors.Add($"Wire source not found: \"{source}\"");
                        }

                        continue;
                    }

                    targetParam.AddSource(sourceParam);
                }
            }

            // Wire cluster output hooks
            var outputHooks = _internalDocument.ClusterOutputHooks() ?? Array.Empty<IGH_Param>();
            foreach (var outDef in response.Outputs)
            {
                var hook = outputHooks.FirstOrDefault(h => h.NickName == outDef.Name);
                if (hook == null)
                {
                    var availableHooks = string.Join(", ", outputHooks.Select(h => $"\"{h.NickName}\""));
                    _lastClusterErrors.Add($"Cluster output hook not found: \"{outDef.Name}\". Available output hooks: [{availableHooks}]");
                    continue;
                }

                var sourceParam = ResolveSource(outDef.From, byId, paramById);
                if (sourceParam == null)
                {
                    int srcDot = outDef.From.IndexOf('.');
                    string srcId = srcDot >= 0 ? outDef.From[..srcDot] : outDef.From;
                    if (byId.TryGetValue(srcId, out var srcComp))
                    {
                        var available = string.Join(", ", srcComp.Params.Output.Select(p => p.NickName));
                        _lastClusterErrors.Add($"Output wire source \"{outDef.From}\" not found. Component \"{srcId}\" ({srcComp.Name}) has outputs: [{available}]");
                    }
                    else
                    {
                        _lastClusterErrors.Add($"Output wire source not found: \"{outDef.From}\"");
                    }

                    continue;
                }

                hook.AddSource(sourceParam);
            }

            // Build panel annotation targets: panel InstanceGuid → component InstanceGuid.
            // Used by HierarchicalLayout to place each panel beside the component it describes.
            var panelTargets = new Dictionary<Guid, Guid>();
            foreach (var (def, param) in resolvedParams)
            {
                if (def.Annotates != null && byId.TryGetValue(def.Annotates, out var targetComp))
                    panelTargets[param.InstanceGuid] = targetComp.InstanceGuid;
            }

            // Assign positions to all inner-document objects using hierarchical layout.
            HierarchicalLayout.Apply(_internalDocument, panelTargets);
        }
        finally
        {
            _internalDocument.RaiseEvents = wasRaisingEvents;
        }
    }

    // Sets persistent data on a standalone parameter component from the nickname string value.
    private static void SetParamValue(IGH_Param param, string? value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return;

        if (param is Param_Number numP
            && double.TryParse(value, NumberStyles.Any, CultureInfo.InvariantCulture, out double d))
            numP.SetPersistentData(new GH_Number(d));
        else if (param is Param_Integer intP
            && int.TryParse(value, out int i))
            intP.SetPersistentData(new GH_Integer(i));
        else if (param is Param_Boolean boolP)
            boolP.SetPersistentData(new GH_Boolean(
                value.Trim().Equals("true", StringComparison.OrdinalIgnoreCase) || value.Trim() == "1"));
        else if (param is Param_String strP)
            strP.SetPersistentData(new GH_String(value));

        param.NickName = value;
    }

    // Resolves a wire source string to the corresponding IGH_Param in the inner document.
    // "input.<name>" → cluster input hook; "<id>.output" → Panel param; "<id>.<nickName>" → component output param.
    private IGH_Param? ResolveSource(string source, Dictionary<string, IGH_Component> byId, Dictionary<string, IGH_Param> paramById)
    {
        int dot = source.IndexOf('.');
        if (dot < 0)
            return null;

        string id = source[..dot];
        string nickName = source[(dot + 1)..];

        if (id.Equals("input", StringComparison.OrdinalIgnoreCase))
        {
            return _internalDocument.ClusterInputHooks()
                ?.FirstOrDefault(h => h.NickName == nickName);
        }

        // Panels and other standalone params are themselves the output; nickName is ignored.
        if (paramById.TryGetValue(id, out var param))
            return param;

        if (byId.TryGetValue(id, out var comp))
            return comp.Params.Output.FirstOrDefault(p => p.NickName == nickName)
                ?? comp.Params.Output.FirstOrDefault(p => string.Equals(p.NickName, nickName, StringComparison.OrdinalIgnoreCase))
                ?? comp.Params.Output.FirstOrDefault(p => string.Equals(p.Name, nickName, StringComparison.OrdinalIgnoreCase));

        return null;
    }

    // Returns the names of all non-core GH libraries currently loaded in the component server.
    private static List<string> GetInstalledPluginNames()
    {
        return Grasshopper.Instances.ComponentServer.Libraries
            .Where(lib => !lib.Name.Equals("Grasshopper", StringComparison.OrdinalIgnoreCase))
            .Select(lib => lib.Name)
            .OrderBy(n => n)
            .ToList();
    }

}
