// Copyright (c) 2026 Physalia Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using GH_IO.Serialization;
using Grasshopper.Kernel;
using Physalia.Core.Parsing;
using Physalia.Core.Prompts;
using Physalia.GH.Attributes;
using Physalia.GH.Helpers;

namespace Physalia.GH.Components;

/// <summary>
/// The ZOOID component executes a Python 3 script generated by a paired COMPOSER component.
/// Its input and output parameters are rebuilt dynamically from the LLM response and can
/// also be extended manually by the user via the variable parameter interface.
/// </summary>
public class PyZooid : ZooidBase
{
    // FIELDS ==========================================================================================
    private readonly ScriptRunner _scriptRunner = new ();
    private ScriptResponse? _lastResponse;
    private bool _needsCheck;
    private string? _lastRuntimeError;

    // PROPERTIES =======================================================================================

    /// <summary>
    /// Gets the unique ID for this component. Do not change this ID after release.
    /// </summary>
    public override Guid ComponentGuid
    {
        get { return new Guid("7CD743AB-E4FC-4396-A190-4559632C4848"); }
    }

    /// <summary>
    /// Gets the pyflakes diagnostics from the last CodeChecker run.
    /// Updated once each time a new script is received from the LLM.
    /// </summary>
    public IReadOnlyList<Diagnostic> LastDiagnostics { get; private set; } = new List<Diagnostic>();

    /// <summary>
    /// Gets the system prompt fragment describing the Python 3 script format and JSON response
    /// schema.
    /// </summary>
    public override string FormatPrompt => SystemPrompt.GetPythonPrompt();

    /// <summary>
    /// Gets the generated Python script from the most recent LLM response, or null if none received.
    /// </summary>
    public override string? State => _lastResponse?.Script;

    /// <summary>
    /// Gets a description of the current script's purpose from its status message,
    /// or null if no response has been received.
    /// </summary>
    public override string? ZooidDescription => _lastResponse?.StatusMessage;

    // CONSTRUCTOR =======================================================================================

    /// <summary>
    /// Initializes a new instance of the <see cref="PyZooid"/> class.
    /// </summary>
    public PyZooid()
      : base(
            "PyZooid",
            "PyZ",
            "Generated Python Script",
            "Core")
    {
    }

    // GH COMPONENT OVERRIDES ============================================================================================

    /// <summary>
    /// No fixed input parameters are registered; all inputs are added dynamically via
    /// <see cref="ApplyLlmResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The input parameter manager (unused).</param>
    protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
    {
    }

    /// <summary>
    /// No fixed output parameters are registered; all outputs are added dynamically via
    /// <see cref="ApplyLlmResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The output parameter manager (unused).</param>
    protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
    {
    }

    /// <summary>
    /// Executes the stored Python 3 script, reading values from dynamic input parameters
    /// and writing results to dynamic output parameters. Does nothing if no LLM response
    /// has been received yet.
    /// </summary>
    /// <param name="DA">Used to read dynamic inputs and write dynamic outputs.</param>
    protected override void SolveInstance(IGH_DataAccess DA)
    {
        if (_lastResponse == null)
        {
            return;
        }

        // Run CodeChecker once per new script, not on every solve
        if (_needsCheck)
        {
            var inputNames = _lastResponse.Inputs.Select(i => i.Name).ToList();
            LastDiagnostics = CodeChecker.Check(_lastResponse.Script, inputNames);
            _needsCheck = false;
        }

        _lastRuntimeError = null;

        try
        {
            _scriptRunner.Execute(DA, _lastResponse);
        }
        catch (Exception ex)
        {
            _lastRuntimeError = ex.Message;
            AddRuntimeMessage(GH_RuntimeMessageLevel.Error, $"Script execution failed: {ex.Message}");
        }
    }

    /// <summary>
    /// Assigns the custom <see cref="ZooidAttrib"/> attribute class to this component.
    /// </summary>
    public override void CreateAttributes() => m_attributes = new ZooidAttrib(this);

    /// <summary>
    /// Appends a Disconnect Composer item to the standard component context menu.
    /// The item is greyed out when no COMPOSER is currently linked to this ZOOID.
    /// </summary>
    /// <param name="menu">The context menu being built.</param>
    public override void AppendAdditionalMenuItems(System.Windows.Forms.ToolStripDropDown menu)
    {
        base.AppendAdditionalMenuItems(menu);

        // search the document for a composer that points at this zooid
        var linkedComposer = FindLinkedComposer();

        var item = Menu_AppendItem(menu, "Disconnect Composer", OnDisconnectComposer, linkedComposer != null);
        item.ToolTipText = "Remove the link between this ZOOID and its COMPOSER.";
    }

    /// <summary>
    /// Re-subscribes rename listeners for all user-defined parameters after the component is loaded into a document.
    /// </summary>
    /// <param name="document">The document this component was added to.</param>
    public override void AddedToDocument(GH_Document document)
    {
        base.AddedToDocument(document);
        SubscribeUserParamEvents(); // used to auto apply python formatting and de-duplicating
    }

    // SERIALIZATION ==========================================================================

    /// <summary>
    /// Serializes the last LLM response so the generated script and parameter definitions
    /// survive save and reload.
    /// </summary>
    /// <param name="writer">The GH_IWriter to write to.</param>
    /// <returns>true.</returns>
    public override bool Write(GH_IWriter writer)
    {
        if (_lastResponse != null)
        {
            writer.SetString("ScriptResponse", JsonSerializer.Serialize(_lastResponse));
        }

        return base.Write(writer);
    }

    /// <summary>
    /// Deserialises the last LLM response. Dynamic parameters are restored automatically
    /// by Grasshopper; this restores the script so <see cref="SolveInstance"/> can execute it.
    /// </summary>
    /// <param name="reader">The GH_IReader to read from.</param>
    /// <returns>true.</returns>
    public override bool Read(GH_IReader reader)
    {
        string json = string.Empty;
        if (reader.TryGetString("ScriptResponse", ref json))
        {
            _lastResponse = JsonSerializer.Deserialize<ScriptResponse>(json);
        }

        return base.Read(reader);
    }

    // LLM RESPONSE AND SCRIPT EDITING ==================================================================

    /// <summary>
    /// Parses the raw LLM response, stores the result, rebuilds the component's dynamic
    /// parameters, and schedules a solution refresh.
    /// </summary>
    /// <param name="rawResponse">The raw JSON string returned by the LLM.</param>
    public override void ApplyLlmResponse(string rawResponse)
    {
        _lastResponse = ResponseParser.Parse(rawResponse);
        LastStatusMessage = _lastResponse.StatusMessage;
        _needsCheck = true;
        if (Params.Input.Count == 0 && Params.Output.Count == 0)
            ParamBuilder.Rebuild(this, _lastResponse);
        ExpireSolution(true);
    }

    /// <summary>
    /// Opens the Eto.Forms script editor dialog for the currently stored script.
    /// </summary>
    public override void OpenEditor()
    {
        if (_lastResponse == null)
        {
            return;
        }

        var inputNames = _lastResponse.Inputs.Select(i => i.Name).ToList();
        var dialog = new ScriptEditorDialog(_lastResponse.Script, inputNames);
        var result = dialog.ShowModal(Grasshopper.Instances.EtoDocumentEditor);

        if (result != null)
        {
            _lastResponse.Script = result;
            Message = "Edited";
            ExpireSolution(true);
        }
    }

    /// <summary>
    /// Builds a complete auto-fix prompt from the current pyflakes diagnostics and runtime
    /// error. Returns null if the script has no errors.
    /// </summary>
    /// <returns>A formatted fix message string, or null if there are no errors.</returns>
    public override string? GetFixMessage()
    {
        bool hasErrors = !string.IsNullOrEmpty(_lastRuntimeError) || LastDiagnostics.Count > 0;
        if (!hasErrors)
        {
            return null;
        }

        var sb = new StringBuilder();
        sb.AppendLine("The script has errors that need fixing. Return a corrected JSON response in the same format.");

        if (LastDiagnostics.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("Static analysis errors:");
            foreach (var d in LastDiagnostics)
            {
                sb.AppendLine($"  {d}");
            }
        }

        if (!string.IsNullOrEmpty(_lastRuntimeError))
        {
            sb.AppendLine();
            sb.AppendLine("Runtime error:");
            sb.AppendLine($"  {_lastRuntimeError}");
        }

        return sb.ToString();
    }

    // RIGHT CLICK MENU HELPERS ===================================================================================================

    // clears the link on the composer side and redraws
    private void OnDisconnectComposer(object sender, EventArgs e)
    {
        var composer = FindLinkedComposer();
        if (composer == null)
        {
            return;
        }

        composer.ZooidComponent = null;
        composer.ZooidGuid = Guid.Empty;
        composer.ExpireSolution(true);
    }
}
