// Copyright (c) 2026 Physalia Contributors
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.RegularExpressions;
using GH_IO.Serialization;
using Grasshopper.Kernel;
using Grasshopper.Kernel.Parameters;
using Physalia.Core.Config;
using Physalia.Core.Parsing;
using Physalia.GH.Attributes;
using Physalia.GH.Helpers;

namespace Physalia.GH.Components;

/// <summary>
/// The ZOOID component executes a Python 3 script generated by a paired CREST component.
/// Its input and output parameters are rebuilt dynamically from the LLM response and can
/// also be extended manually by the user via the variable parameter interface.
/// </summary>
public class Zooid : PhyBase, IGH_VariableParameterComponent
{
    // FIELDS ==========================================================================================
    private readonly ScriptRunner _scriptRunner = new ();
    private ScriptResponse? _lastResponse;
    private bool _needsCheck;

    // PROPERTIES =======================================================================================

    /// <summary>
    /// Gets the unique ID for this component. Do not change this ID after release.
    /// </summary>
    public override Guid ComponentGuid
    {
        get { return new Guid("7CD743AB-E4FC-4396-A190-4559632C4848"); }
    }

    /// <summary>
    /// Gets the pyflakes diagnostics from the last CodeChecker run.
    /// Updated once each time a new script is received from the LLM.
    /// </summary>
    public IReadOnlyList<Diagnostic> LastDiagnostics { get; private set; } = new List<Diagnostic>();

    /// <summary>
    /// Gets the runtime error message from the last failed script execution, or null if the last run succeeded.
    /// </summary>
    public string? LastRuntimeError { get; private set; }

    // CONSTRUCTOR =======================================================================================

    /// <summary>
    /// Initializes a new instance of the <see cref="Zooid"/> class.
    /// </summary>
    public Zooid()
      : base(
            "PyZooid",
            "PyZ",
            "Generated Python Script",
            "Core")
    {
    }

    // GH COMPONENT OVERRIDES ============================================================================================

    /// <summary>
    /// No fixed input parameters are registered; all inputs are added dynamically via
    /// <see cref="ReceiveResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The input parameter manager (unused).</param>
    protected override void RegisterInputParams(GH_Component.GH_InputParamManager pManager)
    {
    }

    /// <summary>
    /// No fixed output parameters are registered; all outputs are added dynamically via
    /// <see cref="ReceiveResponse"/> or by the user through the variable parameter interface.
    /// </summary>
    /// <param name="pManager">The output parameter manager (unused).</param>
    protected override void RegisterOutputParams(GH_Component.GH_OutputParamManager pManager)
    {
    }

    /// <summary>
    /// Executes the stored Python 3 script, reading values from dynamic input parameters
    /// and writing results to dynamic output parameters. Does nothing if no LLM response
    /// has been received yet.
    /// </summary>
    /// <param name="DA">Used to read dynamic inputs and write dynamic outputs.</param>
    protected override void SolveInstance(IGH_DataAccess DA)
    {
        if (_lastResponse == null)
        {
            return;
        }

        // Run CodeChecker once per new script, not on every solve
        if (_needsCheck)
        {
            var inputNames = _lastResponse.Inputs.Select(i => i.Name).ToList();
            LastDiagnostics = CodeChecker.Check(_lastResponse.Script, inputNames);
            _needsCheck = false;
        }

        LastRuntimeError = null;

        try
        {
            _scriptRunner.Execute(DA, _lastResponse);
        }
        catch (Exception ex)
        {
            LastRuntimeError = ex.Message;
            AddRuntimeMessage(GH_RuntimeMessageLevel.Error, $"Script execution failed: {ex.Message}");
        }
    }

    /// <summary>
    /// Assigns the custom <see cref="ZooidAttrib"/> attribute class to this component.
    /// </summary>
    public override void CreateAttributes() => m_attributes = new ZooidAttrib(this);

    /// <summary>
    /// Appends a Disconnect Crest item to the standard component context menu.
    /// The item is greyed out when no CREST is currently linked to this ZOOID.
    /// </summary>
    /// <param name="menu">The context menu being built.</param>
    public override void AppendAdditionalMenuItems(System.Windows.Forms.ToolStripDropDown menu)
    {
        base.AppendAdditionalMenuItems(menu);

        // search the document for a crest that points at this zooid
        var linkedCrest = FindLinkedCrest();

        var item = Menu_AppendItem(menu, "Disconnect Crest", OnDisconnectCrest, linkedCrest != null);
        item.ToolTipText = "Remove the link between this ZOOID and its CREST.";
    }

    /// <summary>
    /// Re-subscribes rename listeners for all user-defined parameters after the component is loaded into a document.
    /// </summary>
    /// <param name="document">The document this component was added to.</param>
    public override void AddedToDocument(GH_Document document)
    {
        base.AddedToDocument(document);
        SubscribeUserParamEvents(); // used to auto apply python formatting and de-duplicating
    }

    // SERIALIZATION ==========================================================================

    /// <summary>
    /// Serializes the last LLM response so the generated script and parameter definitions
    /// survive save and reload.
    /// </summary>
    /// <param name="writer">The GH_IWriter to write to.</param>
    /// <returns>true.</returns>
    public override bool Write(GH_IWriter writer)
    {
        if (_lastResponse != null)
        {
            writer.SetString("ScriptResponse", JsonSerializer.Serialize(_lastResponse));
        }

        return base.Write(writer);
    }

    /// <summary>
    /// Deserialises the last LLM response. Dynamic parameters are restored automatically
    /// by Grasshopper; this restores the script so <see cref="SolveInstance"/> can execute it.
    /// </summary>
    /// <param name="reader">The GH_IReader to read from.</param>
    /// <returns>true.</returns>
    public override bool Read(GH_IReader reader)
    {
        string json = string.Empty;
        if (reader.TryGetString("ScriptResponse", ref json))
        {
            _lastResponse = JsonSerializer.Deserialize<ScriptResponse>(json);
        }

        return base.Read(reader);
    }

    // LLM RESPONSE AND SCRIPT EDITING ==================================================================

    /// <summary>
    /// Stores the latest LLM response, rebuilds the component's dynamic parameters,
    /// and schedules a solution refresh.
    /// </summary>
    /// <param name="response">The parsed LLM response containing the script and parameter definitions.</param>
    public void ReceiveResponse(ScriptResponse response)
    {
        _lastResponse = response;
        _needsCheck = true;
        ParamBuilder.Rebuild(this, response);
        ExpireSolution(true);
    }

    /// <summary>
    /// Opens the Eto.Forms script editor dialog for the currently stored script.
    /// </summary>
    public void OpenScriptEditor()
    {
        if (_lastResponse == null)
        {
            return;
        }

        var inputNames = _lastResponse.Inputs.Select(i => i.Name).ToList();
        var dialog = new ScriptEditorDialog(_lastResponse.Script, inputNames);
        var result = dialog.ShowModal(Grasshopper.Instances.EtoDocumentEditor);

        if (result != null)
        {
            _lastResponse.Script = result;
            Message = "Edited";
            ExpireSolution(true);
        }
    }

    // PARAMETER BUILDERS ======================================================================================

    /// <summary>
    /// Always returns true; users may insert parameters on either side at any index.
    /// </summary>
    /// <param name="side">The parameter side (input or output).</param>
    /// <param name="index">The insertion index.</param>
    /// <returns>true.</returns>
    public bool CanInsertParameter(GH_ParameterSide side, int index)
    {
        return true;
    }

    /// <summary>
    /// Always returns true; users may remove any parameter from either side.
    /// </summary>
    /// <param name="side">The parameter side (input or output).</param>
    /// <param name="index">The index of the parameter to remove.</param>
    /// <returns>true.</returns>
    public bool CanRemoveParameter(GH_ParameterSide side, int index)
    {
        return true;
    }

    /// <summary>
    /// Creates a new generic parameter when the user adds one manually.
    /// Inputs are named "in_N" and outputs "out_N", where N is the lowest available integer.
    /// </summary>
    /// <param name="side">The side on which the parameter will be created.</param>
    /// <param name="index">The index at which the parameter will be inserted.</param>
    /// <returns>A new Param_GenericObject with a unique auto-incremented name.</returns>
    public IGH_Param CreateParameter(GH_ParameterSide side, int index)
    {
        if (side == GH_ParameterSide.Input)
        {
            string nick = NextParamName("in", Params.Input.Select(p => p.NickName));
            return new Param_GenericObject { Name = nick, NickName = nick, Description = "user defined parameter", Optional = true };
        }
        else
        {
            string nick = NextParamName("out", Params.Output.Select(p => p.NickName));
            return new Param_GenericObject { Name = nick, NickName = nick, Description = "user defined parameter", Optional = true };
        }
    }

    /// <summary>
    /// Always returns true; no cleanup is required when a parameter is removed.
    /// </summary>
    /// <param name="side">The side from which the parameter is being removed.</param>
    /// <param name="index">The index of the parameter being removed.</param>
    /// <returns>true.</returns>
    public bool DestroyParameter(GH_ParameterSide side, int index)
    {
        return true;
    }

    /// <summary>
    /// Sanitizes the names of all parameters to valid Python identifiers after any parameter change.
    /// Also subscribes to <see cref="OnUserParamChanged"/> for any newly added user params.
    /// </summary>
    public void VariableParameterMaintenance()
    {
        var userParams = Params.Input.Concat(Params.Output).ToList();
        var taken = new HashSet<string>();

        foreach (var p in userParams)
        {
            var clean = SanitizePythonName(p.NickName);
            clean = Deduplicate(clean, taken);
            taken.Add(clean);

            if (clean != p.NickName)
            {
                p.Name = clean;
                p.NickName = clean;
            }
        }

        SubscribeUserParamEvents();
    }

    // makes sure the input names are proper python variables
    private static string SanitizePythonName(string name)
    {
        // Replace any non-alphanumeric/underscore character (including spaces) with _
        var clean = Regex.Replace(name, @"[^a-zA-Z0-9_]", "_");

        // Collapse runs of underscores and trim leading/trailing ones
        clean = Regex.Replace(clean, @"_+", "_").Trim('_');

        if (string.IsNullOrEmpty(clean))
        {
            return "param";
        }

        // Python identifiers cannot start with a digit — check after trimming
        if (char.IsDigit(clean[0]))
        {
            clean = "_" + clean;
        }

        return clean;
    }

    // can't have duplicate names - ensures no duplicates
    private static string Deduplicate(string name, HashSet<string> taken)
    {
        if (!taken.Contains(name))
        {
            return name;
        }

        int i = 1;
        string candidate;
        do
        {
            candidate = $"{name}_{i++}";
        }
        while (taken.Contains(candidate));

        return candidate;
    }

    // default parameter names when adding param with the little + symbol appends a number
    private static string NextParamName(string prefix, IEnumerable<string> existingParams)
    {
        // check to see the next available param name
        for (int i = 0; ; i++)
        {
            string candidate = $"{prefix}_{i}";
            if (!existingParams.Contains(candidate))
            {
                return candidate;
            }
        }
    }

    // subscribe to parameter changes - used for auto-updating the python names
    private void SubscribeUserParamEvents()
    {
        foreach (var p in Params.Input.Concat(Params.Output))
        {
            // Unsubscribe first to avoid double-subscribing
            p.ObjectChanged -= OnUserParamChanged;
            p.ObjectChanged += OnUserParamChanged;
        }
    }

    private void OnUserParamChanged(IGH_DocumentObject sender, GH_ObjectChangedEventArgs e)
    {
        if (e.Type != GH_ObjectEventType.NickName)
        {
            return;
        }

        if (sender is not IGH_Param p)
        {
            return;
        }

        var clean = SanitizePythonName(p.NickName);

        // Build taken set from all other params
        var taken = new HashSet<string>(
            Params.Input.Concat(Params.Output)
                .Where(other => other != p)
                .Select(other => other.NickName));

        clean = Deduplicate(clean, taken);

        if (clean == p.NickName)
        {
            return;
        }

        // Unsubscribe to avoid re-entrancy when setting NickName
        p.ObjectChanged -= OnUserParamChanged;
        p.Name = clean;
        p.NickName = clean;
        p.ObjectChanged += OnUserParamChanged;
    }

    // RIGHT CLICK MENU HELPERS ===================================================================================================

    // walks the document to find the crest that is currently pointing at this zooid
    private Crest? FindLinkedCrest()
    {
        return OnPingDocument()?.Objects
            .OfType<Crest>()
            .FirstOrDefault(c => c.ZooidComponent?.InstanceGuid == InstanceGuid);
    }

    // clears the link on the crest side and redraws
    private void OnDisconnectCrest(object sender, EventArgs e)
    {
        var crest = FindLinkedCrest();
        if (crest == null)
        {
            return;
        }

        crest.ZooidComponent = null;
        crest.ZooidGuid = Guid.Empty;
        crest.ExpireSolution(true);
    }
}
