<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
    <!-- Select the framework(s) you wish to target.
        Rhino 6: net45
        Rhino 7: net48
        Rhino 8 Windows: net48, net7.0, net7.0-windows, net7.0-windows10.0.22000.0, etc
        Rhino 8 Mac: net7.0, net7.0-macos, net7.0-macos12.0, etc
    -->
    <TargetFramework>net7.0-windows</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <TargetExt>.gha</TargetExt>
    <NoWarn>NU1701</NoWarn>
	<!-- We need to supress the below to avoid the system.drawing warnings for Mac. Rhino implements system.drawing in Mac. 
	https://discourse.mcneel.com/t/system-drawing-common-not-compatible-with-macos-anymore/166565 
	-->
	<NoWarn>$(NoWarn);CA1416</NoWarn>
	<UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  
  <PropertyGroup>
    <!-- Specifies information for Assembly and Yak -->
    <Version>1.0</Version>
    <Title>Physalia.GH</Title>
    <Company>Physalia.GH Authors</Company>
    <Description>Description of Physalia.GH</Description>
  </PropertyGroup>
  
  <ItemGroup>
    <Compile Remove="Goo\**" />
    <EmbeddedResource Remove="Goo\**" />
    <None Remove="Goo\**" />
  </ItemGroup>
  
  <ItemGroup>
    <None Remove="Resources\brain.png" />
    <None Remove="Resources\cluster.png" />
    <None Remove="Resources\model.png" />
    <None Remove="Resources\provider.png" />
    <None Remove="Resources\python.png" />
    <None Remove="Resources\transmitter.png" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="8.0.23304.9001" ExcludeAssets="runtime" />
<PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Physalia.Core\Physalia.Core.csproj" />
  </ItemGroup>

	<ItemGroup>
		<!-- The Python script execution engine -->
		<Reference Include="Rhino.Runtime.Code">
			<HintPath>C:\Program Files\Rhino 8\System\Rhino.Runtime.Code.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Include="Resources\brain.png" />
	  <EmbeddedResource Include="Resources\cluster.png" />
	  <EmbeddedResource Include="Resources\model.png" />
	  <EmbeddedResource Include="Resources\provider.png" />
	  <EmbeddedResource Include="Resources\python.png" />
	  <EmbeddedResource Include="Resources\transmitter.png" />
	</ItemGroup>
    
	<!-- The python script that populated the model .json-->
	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="python &quot;$(SolutionDir)scripts\update_model_info.py&quot; &quot;$(TargetDir)model_info.json&quot;" ContinueOnError="WarnAndContinue" />
	</Target>
  
</Project>