<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
    <!-- Select the framework(s) you wish to target.
        Rhino 6: net45
        Rhino 7: net48
        Rhino 8 Windows: net48, net7.0, net7.0-windows, net7.0-windows10.0.22000.0, etc
        Rhino 8 Mac: net7.0, net7.0-macos, net7.0-macos12.0, etc
    -->
    <TargetFramework>net7.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <TargetExt>.gha</TargetExt>
    <NoWarn>NU1701</NoWarn>
  </PropertyGroup>
  
  <PropertyGroup>
    <!-- Specifies information for Assembly and Yak -->
    <Version>1.0</Version>
    <Title>Physalia.GH</Title>
    <Company>Physalia.GH Authors</Company>
    <Description>Description of Physalia.GH</Description>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="8.0.23304.9001" ExcludeAssets="runtime" />
	<PackageReference Include="System.Drawing.Common" Version="7.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Physalia.Core\Physalia.Core.csproj" />
  </ItemGroup>

	<ItemGroup>
		<!-- The Python script execution engine -->
		<Reference Include="Rhino.Runtime.Code">
			<HintPath>C:\Program Files\Rhino 8\System\Rhino.Runtime.Code.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
  
</Project>